[#_kerberos_authentication_pulsarkerberos_reference]
= Kerberos authentication
:imagesdir: _images

When the cluster has Kerberos authentication enabled configure Kerberos settings for DataStax Apache Pulsar™ Connector.

When the cluster has Kerberos authentication enabled, configure these authentication settings.

NOTE: When link:https://docs.datastax.comen/dse/6.8//dse-admin/datastax_enterprise/config/configDseYaml.html#configDseYaml__authorizationOptions[authorization is enabled], the DataStax connector login role must have a minimum of `modify` privileges on tables receiving data from the DataStax Apache Pulsar® Connector.

[#_parameters_synopsis_section]
== Parameters

[source,no-highlight]
----
auth.provider=GSSAPI
auth.gssapi.keyTab=path\_to\_keytab
auth.gssapi.principal=connectorPrincipal/hostname@EXAMPLE.com
auth.gssapi.service=dse
----

auth.provider:: Select the type of authentication provider configured for the DataStax cluster.
+
-   **None** - No authentication.
-   **DSE** - Internal or LDAP authentication.
-   **GSSAPI** - Supports SASL authentication to DSE clusters using the GSSAPI mechanism \(Kerberos authentication\)
+
NOTE: When using the GSSAPI, the Pulsar Connect process requires that the Kerberos configuration file krb5.conf location is provided in the `java.security.krb5.conf` system property at startup. See xref:ROOT:secPulsarKerberosAuth.adoc[].

....
Default: `None`
....

auth.gssapi.keyTab:: Path to the Kerberos key tab file.

auth.gssapi.principal::
Kerberos principal name.
Specifying the principal explicitly to the connector is required if there are multiple principals that have valid tickets in the ticket cache.
Prevents the connector from arbitrarily choosing one.

auth.gssapi.service:: SASL service name to use for GSSAPI provider authentication.

 Default: `dse`
