[#_ssl_encrypted_connection_pulsarssl_reference]
= SSL encrypted connection
:imagesdir: _images

When the cluster has client encryption enabled configure the SSL keys and certificates for the DataStax Apache Pulsar™ Connector.

When the cluster has client encryption enabled, configure the SSL keys and certificates for the DataStax Apache Pulsar™ Connector.

TIP: SSL encryption settings are configured in the link:/en/dse/6.7/dse-admin/datastax_enterprise/config/configCassandra_yaml.html#configCassandra_yaml__clientEncryptSection[Client-to-node encryption options].
See link:/en/dse/6.7/dse-admin/datastax_enterprise/security/secSslTOC.html[Configuring SSL].

NOTE: You cannot use this option if specifying the link:pulsarConnector.md#secure_ConnectBundle[cloud.secureConnectBundle] option for connecting to a DataStax Astra database.

[#_parameters_synopsis_section]
== Parameters {#synopsis .section}

[source,no-highlight]
----
ssl.provider=None
ssl.cipherSuites=
ssl.hostnameValidation=true
ssl.keystore.password=

# Path to the keystore file.
#ssl.keystore.path=

# Truststore password.
#ssl.truststore.password=

# Path to the truststore file.
#ssl.truststore.path=

# Path to the SSL certificate file, when using OpenSSL.
#ssl.openssl.keyCertChain=

# Path to the private key file, when using OpenSSL.
#ssl.openssl.privateKey=
----

ssl.provider::
SSL provider to use, if any.
Valid choices:

....
-   None
-   JDK
-   OpenSSL

Defaults to None
....

ssl.hostnameValidation:: Whether to validate node hostnames when using SSL.

 Defaults to true

ssl.cipherSuites::
The cipher suites to enable.
Defaults to none, resulting in a "minimal quality of service" according to JDK documentation.

ssl.keystore.password:: Keystore password.

ssl.keystore.path:: Path to the keystore file.

ssl.openssl.keyCertChain:: Path to the SSL certificate file, when using OpenSSL.

ssl.openssl.privateKey:: Path to the private key file, when using OpenSSL.

ssl.truststore.password:: Truststore password.

ssl.truststore.path:: Path to the truststore file.
