= Mapping basic messages to table columns

When messages are created using a Basic or primitive serializer, the message contains a key-value pair. Map the key and value to table columns. Ensure that the data types of the message field are compatible with the data type of the target column.

For example, the Pulsar world topic (`world_topic`) contains 5 records with a key-value pair in each.
The key is an integer and the value is text.

== Table requirements


When mapping fields to columns the data in the Pulsar field must be compatible with the database table column's xref:dse-6.9@cql:reference:data-types.adoc[data type].
Additionally, the Pulsar field mapped to a table's primary key (PK) column must always contain data because primary key columns don't allow nulls.

. Create a keyspace in your database.
+
This example creates a keyspace named `world_keyspace`:
+
[source,bash]
----
cqlsh -e "CREATE KEYSPACE world_keyspace \
  WITH replication = {'class': 'NetworkTopologyStrategy', \
  'Cassandra': 1};"
----
+
For DSE and Cassandra clusters, make sure that the keyspace is replicated to a datacenter set in the connector's `xref:cfgRefPulsarDseConnection.adoc[contactPoints]` parameter.
DSE datacenter names are case sensitive.
Use `xref:dse:managing:tools/nodetool/ring.adoc[nodetool ring]` to get a list of datacenters.

. Create a table.
+
This example creates a table named `world_table` with two columns:
+
[source,bash]
----
cqlsh -e "CREATE TABLE world_table (recordid int PRIMARY KEY, continent text);"
----

. For DSE, verify that all nodes have the same schema version using `xref:dse:managing:tools/nodetool/describe-ring.adoc[nodetool describering]`.
+
For example, this command verifies the schema for `world_keyspace`:
+
[source,bash]
----
nodetool describering -- world_keyspace
----

. In the DataStax Connector configuration file, add the Pulsar topic name to `xref:cfgRefPulsarDseTable.adoc#topics[topics]`, and define the xref:cfgRefPulsarDseTable.adoc#mapping[field-to-column mapping].
+
The following example is maps the `world_topic` to the `world_table` using the minimum required settings:
+
[source,yaml]
----
tasks.max: 1
topics: world_topic
topic:
  world_topic:
    world_keyspace:
      world_table:
        mapping: 'recordid=key, continent=value'
----

. Use `xref:ROOT:opsPulsarAboutOperations.adoc#pulsar-admin-sinks-update[pulsar-admin sinks update]` to apply the new configuration.