= Map basic messages

When messages are created using a basic or primitive serializer, the message contains a key-value pair.
Map the key and value to table columns.

== Mapping requirements

When mapping fields to columns, the following requirements apply:

* The data in the {pulsar-short} field must be compatible with the mapped column's xref:dse-6.9@cql:reference:data-types.adoc[data type].
For example, a string field cannot map to a number column.

* A {pulsar-short} field mapped to a table's primary key (PK) column must always contain data because primary key columns don't allow nulls.

* All primary key columns must have a mapping because primary key columns don't allow nulls.

== Basic mapping example

In this example, a {pulsar-short} topic named `world_topic` contains five records with a key-value pair in each.
The key is an integer and the value is text.

. Create a keyspace in your database.
+
This example creates a keyspace named `world_keyspace`:
+
[source,bash]
----
cqlsh -e "CREATE KEYSPACE world_keyspace \
  WITH replication = {'class': 'NetworkTopologyStrategy', \
  'Cassandra': 1};"
----
+
For {dse-short} and {cass-short} clusters, make sure that the keyspace is replicated to a datacenter set in the {product-short}'s `xref:cfgRefPulsarDseConnection.adoc[contactPoints]` parameter.
{dse-short} datacenter names are case sensitive.
Use `xref:dse:managing:tools/nodetool/ring.adoc[nodetool ring]` to get a list of datacenters.

. Create a table.
+
This example creates a table named `world_table` with two columns:
+
[source,bash]
----
cqlsh -e "CREATE TABLE world_table (recordid int PRIMARY KEY, continent text);"
----

. For {dse-short}, verify that all nodes have the same schema version using `xref:dse:managing:tools/nodetool/describe-ring.adoc[nodetool describering]`.
+
For example, this command verifies the schema for `world_keyspace`:
+
[source,bash]
----
nodetool describering -- world_keyspace
----

. In the {product} configuration file, add the {pulsar-short} topic name to `xref:cfgRefPulsarDseTable.adoc#topics[topics]`, and define the xref:cfgRefPulsarDseTable.adoc#mapping[field-to-column mapping].
+
The following example is maps the `world_topic` to the `world_table` using the minimum required settings:
+
[source,yaml]
----
tasks.max: 1
topics: world_topic
topic:
  world_topic:
    world_keyspace:
      world_table:
        mapping: 'recordid=key, continent=value'
----

. Use `xref:ROOT:opsPulsarAboutOperations.adoc#pulsar-admin-sinks-update[pulsar-admin sinks update]` to apply the new configuration.