[#_ssl_encrypted_connection_pulsarssl_reference]
= SSL encrypted connection
:imagesdir: _images

When the cluster has client encryption enabled, configure the SSL keys and certificates for the DataStax Apache Pulsar™ Connector.

TIP: SSL encryption settings are configured in the link:https://docs.datastax.comen/dse/6.8//dse-admin/datastax_enterprise/config/configCassandra_yaml.html#configCassandra_yaml__clientEncryptSection[Client-to-node encryption options].
See link:https://docs.datastax.comen/dse/6.8//dse-admin/datastax_enterprise/security/secSslTOC.html[Configuring SSL].

NOTE: You cannot use this option if specifying the link:pulsarConnector.md#secure_ConnectBundle[cloud.secureConnectBundle] option for connecting to a DataStax Astra database.

[#_parameters_synopsis_section]
== Parameters

[source,language-yaml]
----
ssl:
  provider: None
  cipherSuites:
  hostnameValidation: true
  keystore:
    password:
    path:
  truststore:
    password:
    path:
  openssl:
    keyCertChain:
    privateKey:
----

provider::
SSL provider to use, if any.
Valid choices:
-   None
-   JDK
-   OpenSSL
+
Defaults to None

hostnameValidation:: Whether to validate node hostnames when using SSL.
+
Defaults to true

cipherSuites:: The cipher suites to enable.
+
Defaults to none, resulting in a "minimal quality of service" according to JDK documentation.

keystore: password:: Keystore password.

keystore: path:: Path to the keystore file.

openssl: keyCertChain:: Path to the SSL certificate file, when using OpenSSL.

openssl: privateKey:: Path to the private key file, when using OpenSSL.

truststore: password:: Truststore password.

truststore: path:: Path to the truststore file.
