= Internal or LDAP authentication

When the cluster has internal or LDAP authentication enabled, configure the user name and password settings for DataStax Apache Pulsar(TM) Connector.
A login role for the connector with access to the mapped tables is also required.

[#ldap-parameters]
== Parameters

[source,yaml]
----
auth:
  provider: DSE
  username: login_role
  password: password
----

provider:: Select the type of authentication provider configured for the DataStax cluster.
-   **None** - No authentication.
-   **DSE** - Internal or LDAP authentication.
-   **GSSAPI** - Supports SASL authentication to DSE clusters using the GSSAPI mechanism \(Kerberos authentication\)
+
When using GSSAPI, the Pulsar Connect process requires that the Kerberos configuration file `krb5.conf` location is provided in the `java.security.krb5.conf` system property at startup. See xref:ROOT:ecPulsarInternalLdapAuth.adoc[].
+
Default: `None`

username:: DSE login role name or LDAP username.Astra database username.
+
When xref:6.9@dse:managing:configure/configure-dse-yaml.adoc#authorizationOptions[authorization is enabled], the DataStax connector login role must have a minimum of `modify` privileges on tables receiving data from the DataStax Apache Pulsar(TM) Connector.

password:: Login role or LDAP password.Astra database password for the specified username.
