= DataStax Apache Pulsar Connector connection parameters
:navtitle: Connection parameters

Use the connection parameters to configure the connection settings from Apache Pulsar(TM) to your database cluster:

[source,yaml]
----
 connectionPoolLocalSize: 4
 contactPoints: [dse_host_list]
 loadBalancing.localDc: datacenter_name
 port: 9042
 maxConcurrentRequests: 500
 maxNumberOfRecordsInBatch: 32
 queryExecutionTimeout: 30
 jmx: true
 compression: None
----

connectionPoolLocalSize:: Number of connections that driver maintains within a connection pool to each node in the local datacenter.
+
Default: `4`

contactPoints:: Either `localhost` or a comma-separated list of host names or IP addresses in square brackets.
If you provide a list of hosts, you must also set `loadBalancing.localDc`.
+
Default: `localhost`

loadBalancing.localDc:: The case-sensitive datacenter name for the driver to use for load balancing.
+
When connecting to Astra with `xref:ROOT:secPulsarInternalLdapAuth.adoc[cloud.secureConnectBundle]`, leave this property unset.
+
Default: `""`

port:: DSE native transport port.
See `xref:6.9@dse:managing:configure/configure-cassandra-yaml.adoc#native-transport-cql-binary-protocol[native_transport_port]`.
+
Default: `9042`

maxConcurrentRequests:: Maximum number of requests to send to DSE at the same time.
+
Default: `500`

maxNumberOfRecordsInBatch:: Number of records to include in a write request to the database table.
+
Default: `32`

jmx:: Whether to enable metrics reporting using Java Management Extensions (JMX).
+
Default: `true`

compression:: Compression algorithm to use when issuing requests to the database server.
Valid values are `None`, `Snappy`, and `LZ4`, which is applied per connector instance.
+
Default: `None`

queryExecutionTimeout:: CQL statement execution timeout, in seconds.
+
Default: `30`