= DataStax Apache Pulsar Connector details

Set the common DataStax Apache Pulsar™ Connector parameters.
See the https://pulsar.apache.org/documentation/#connect_configuring[Configuring Connectors] section of the Apache Pulsar documentation.

[#_parameters_synopsis_section]
== Parameters

[source,language-yaml]
----
tasks.max=1
cloud.secureConnectBundle=/path/to/secure-connect-database_name.zip
----

tasks.max::
Maximum number of tasks created for the connector instance.
The connector can create fewer tasks if it cannot achieve this level of parallelism.
+
NOTE: Use additional Pulsar Connect workers to scale the connector when more throughput is needed. For connector instances to split tasks, they must have the same `group.id`, which is configured in the connect-distributed.properties file. Parallelism is limited by the partitions of the Pulsar topic.
+
Default: `1`

cloud.secureConnectBundle::
The full path to the secure connect bundle for your DataStax Astra database (secure-connect-database_name.zip).
Download the secure connect bundle from the DataStax Cloud console.
+
If this option is specified, you must also include the auth.username and auth.password for the database user.

== Using base64 encoded file

You can encode your zip file using the standard base64 tool.
This is particularly useful because with the absolute file path approach you have to deploy your zip to every machine
that is executing the Connector.
If you encode the file to base64 you supply that file only once and Pulsar Functions Framework will take care of deploying it to the relevant machines.

----
base64 -i bundle.zip
----

Then you can fill cloud.secureConnectBundle with the result of the command

----
tasks.max=1
cloud.secureConnectBundle=base64:UEsDBBQACAAIADmJJ1IAAAAAAAAAAAAAAAAGAAkAY2EuY3J0VVQFAAFeQPdfZJTJjvI4HMTveYq5t0bZoTl8Bzt2giEOOGQh3Mi+sgVw4qcf0a25zPj2L0s/VUml+vvzIHaI95eF/YDYxAIB/lElSgi2kGWBt1UBTiCoiAUvIUcs2WyvJ1K/Mw8w7EIGeHVmkyXABlZeBEESgD4KJMpGbrEERYwRzDeIBTikkDhADTGcqBtq9it3cMW0qc4GPOEA7H8B18DCfi3ljh3kjm1QZnAEfkAu5hFKnZV6QvaeYuUHBibPSTT8OsWblmqbJgm6pzfQWaKNo......
----
