[#pulsarRecordCountMetrics]
= Metrics for the processed Pulsar topic records
:imagesdir: _images

Use the Record Count MBeans to monitor the total number of Apache Pulsar™ records processed by the DataStax Connector.

NOTE: To capture these metrics, the xref:cfgRefPulsarDseConnection.adoc[jmx] parameter must be set to `true` in the DataStax Apache Pulsar® Connector configuration file.

Count:: Running total of records processed.
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector_name,name=topic.keyspace.table.recordCount' attribute='Count'
----
+
where
+
-  connector_name - DataStax Apache Pulsar® Connector xref:configuration_reference/cfgRefPulsarConnector.adoc[name].

MeanRate:: Average number of records processed since the connector was created.
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector_name,name=topic.keyspace.table.recordCount' attribute='MeanRate'
----
+
where
+
-  connector_name - DataStax Apache Pulsar® Connector xref:configuration_reference/cfgRefPulsarConnector.adoc[name].

OneMinuteRate:: Moving average of records processed in the last minute.
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector_name,name=topic.keyspace.table.recordCount' attribute='OneMinuteRate'
----
+
where
+
-  connector_name - DataStax Apache Pulsar® Connector xref:configuration_reference/cfgRefPulsarConnector.adoc[name].

FiveMinuteRate:: Moving average of records processed in the last five minutes.
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,name=topic.keyspace.table.recordCount' attribute='FiveMinuteRate'
----
+
where
+
- connector_name - DataStax Apache Pulsar® Connector xref:configuration_reference/cfgRefPulsarConnector.adoc[name].

FifteenMinuteRate:: Moving average of records processed in the last fifteen minutes.
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector_name,name=topic.keyspace.table.recordCount' attribute='FifteenMinuteRate'
----
+
where
+
- connector_name - DataStax Apache Pulsar® Connector xref:configuration_reference/cfgRefPulsarConnector.adoc[name].
