= Write requests to the DataStax platform

Sessions details and write request metrics

== CQL requests

The MBean path is:

[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-requests'
----

where

* connector_name - DataStax Apache Pulsar® Connector link:../configuration_reference/pulsarConnector.md#name[name].
* session_id - Internal session id used by the connector;
for example: `s0`.

Latency histogram

The latency histogram uses a snapshot of data from the most recent 30 second interval.

The following attributes make up the CQL request latency histogram:

50thPercentile:: The attribute is:
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-requests' attribute='50thPercentile'
----

75thPercentile:: The attribute is:
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-requests' attribute='75thPercentile'
----

95thPercentile:: The attribute is:
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-requests' attribute='95thPercentile'
----

98thPercentile:: The attribute is:
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-requests' attribute='98thPercentile'
----

99thPercentile:: The attribute is:
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-requests' attribute='99thPercentile'
----

999thPercentile:: The attribute is:
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-requests' attribute='999thPercentile'
----

== Throughput

Throughput metrics measured by the connector instance when writing to the DataStax platform.
The measurements are writes per second (not records per second).
The connector uses a CQL batch to write to the DataStax platform.
Multiple records are included single batch;
the default is 32.

MeanRate:: Average writes-per-second.
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector_name,driver=driver,session=session_id,name=cql-requests' attribute='MeanRate''
----

== Write count

Running total of batched write requests sent by the connector to the DataStax platform.

Count:: Total number of write requests sent to the DataStax platform by the connector.
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector_name,driver=driver,session=session_id,name=cql-requests' attribute='Count'
----

TIP: The write count can differ from xref:monPulsarRecordCountMetrics.adoc[recordCount] because the driver uses a batch statement that can include multiple records.


== CQL client timeouts

The `cql-client-timeouts` MBean provides the number of timeouts that occur when writing to the DataStax platform.

NOTE: Connector continuously retries timeouts;
therefore the count does not indicate write failures.

The MBean path is:

[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-client-timeouts'
----

where

* connector_name - DataStax Apache Pulsar® Connector link:../configuration_reference/pulsarConnector.md#name[name].
* session_id - Internal session id used by the connector;
for example: `s0`.

The attribute is:

Count:: Running total of the number of requests that timed out when communicating with a node.
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=connector\_name,driver=driver,session=session\_id,name=cql-client-timeouts' attribute='Count'
----
