[#pulsarRecordCountMetrics]
= Metrics for the processed Pulsar topic records
:imagesdir: _images

Running total and averages of the Pulsar topic records processed by the DataStax Pulsar Connector.

Use the Record Count MBeans to monitor the total number of Apache Pulsar™ records processed by the DataStax Connector.

NOTE: To capture these metrics, the link:../configuration_reference/pulsarDseConnection.md#jmx[jmx] parameter must be set to `true` in the DataStax Apache Pulsar® Connector configuration file.

Count:: Running total of records processed.

....
```no-highlight
objectName='com.datastax.pulsarconnector:connector=connector\_name,name=topic.keyspace.table.recordCount' attribute='Count'
```

where

-   connector\_name - DataStax Apache Pulsar® Connector [name](../configuration_reference/pulsarConnector.md#name).
....

MeanRate:: Average number of records processed since the connector was created.

....
```no-highlight
objectName='com.datastax.pulsarconnector:connector=connector\_name,name=topic.keyspace.table.recordCount' attribute='MeanRate'
```

where

-   connector\_name - DataStax Apache Pulsar® Connector [name](../configuration_reference/pulsarConnector.md#name).
....

OneMinuteRate:: Moving average of records processed in the last minute.

....
```no-highlight
objectName='com.datastax.pulsarconnector:connector=connector\_name,name=topic.keyspace.table.recordCount' attribute='OneMinuteRate'
```

where

-   connector\_name - DataStax Apache Pulsar® Connector [name](../configuration_reference/pulsarConnector.md#name).
....

FiveMinuteRate:: Moving average of records processed in the last five minutes.

....
```no-highlight
objectName='com.datastax.pulsarconnector:connector=connector\_name,name=topic.keyspace.table.recordCount' attribute='FiveMinuteRate'

```

where

-   connector\_name - DataStax Apache Pulsar® Connector [name](../configuration_reference/pulsarConnector.md#name).
....

FifteenMinuteRate:: Moving average of records processed in the last fifteen minutes.

....
```no-highlight
objectName='com.datastax.pulsarconnector:connector=connector\_name,name=topic.keyspace.table.recordCount' attribute='FifteenMinuteRate'
```

where

-   connector\_name - DataStax Apache Pulsar® Connector [name](../configuration_reference/pulsarConnector.md#name).
....
