[#pulsarMetricsFailed]
= Failed Pulsar topic record metrics
:imagesdir: _images

You can use DataStax Apache Pulsar™ Connector metrics to return a running total, or moving averages per a specified rate, of Pulsar topic records that the connector instance failed to process because the mapping could not be interpreted.

DataStax Apache Pulsar Connector provides two Mbeans for failed record counts:

* {blank}
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=*,name=topic.keyspace.table.failedRecordCount'
----
* {blank}
+
[source,no-highlight]
----
objectName='com.datastax.pulsarconnector:connector=*,name=failedRecordsWithUnknownTopic'
----

The `failedRecordCount` Mbean is incremented when Pulsar Connector is able to detect that there was a failure for a specific topic, keyspace, table;
which is the majority case.
The `failedRecordsWithUnknownTopic` Mbean is incremented when Pulsar Connector was not able to detect the Pulsar topic that was associated with a failed record;
this is an edge case.

[#_failed_record_metric_attributes_pulsarmetricsattributesfailedrecords_section]
== Failed Record Metric Attributes

Count:: Running total of the number of failed records encountered by the connector instance:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=topic.keyspace.table.failedRecordCount'
  attribute='Count'
----
+
Running total of the number of failed records encountered by the connector where the Pulsar topic was unknown:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=failedRecordsWithUnknownTopic'
  attribute='Count'
----

OneMinuteRate:: Moving average of records that failed in the last minute:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=topic.keyspace.table.failedRecordCount'
  attribute='OneMinuteRate'
----
+
Moving average of records that failed in the last minute where the Pulsar topic was unknown:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=failedRecordsWithUnknownTopic'
  attribute='OneMinuteRate'
----

FiveMinuteRate:: Moving average of records that failed in the last five minutes.
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=topic.keyspace.table.failedRecordCount'
  attribute='FiveMinuteRate'
----
+
Moving average of records that failed in the last five minutes where the Pulsar topic was unknown:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=failedRecordsWithUnknownTopic'
  attribute='FiveMinuteRate'
----

FifteenMinuteRate:: Moving average of records that failed in the last 15 minutes:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=topic.keyspace.table.failedRecordCount'
  attribute='FifteenMinuteRate'
----
+
Moving average of records that failed in the last 15 minutes where the Pulsar topic was unknown:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=failedRecordsWithUnknownTopic'
  attribute='FifteenMinuteRate'
----

MeanRate:: The mean average number of records that failed since this Pulsar Connector instance was created:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=topic.keyspace.table.failedRecordCount'
  attribute='MeanRate'
----
+
Mean average of records that failed since this Pulsar Connector instance was created, where the Pulsar topic was unknown:
+
[source,no-highlight]
----
 objectName='com.datastax.pulsarconnector:connector=*,name=failedRecordsWithUnknownTopic'
  attribute='FifteenMinuteRate'
----
+
TIP: See `WARN` level message that includes specific information for each record in the Pulsar Connect worker log.
