= Delete the DataStax Apache Pulsar(TM) connector
:navtitle: Delete the Pulsar connector

To completely remove the DataStax Apache Pulsar(TM) connector, do the following:

. Delete any sinks associated with the connector:
+
[source,bash,subs="+quotes"]
----
bin/pulsar-admin sinks delete --name **SINK_NAME** --namespace **SINK_NAMESPACE** --tenant **SINK_TENANT**
----
+
Replace the following:
+
* `**SINK_NAME**`: The name of the Pulsar sink to delete
* `**SINK_NAMESPACE**`: The name of the Pulsar namespace associated with the sink
* `**SINK_TENANT**`: The name of the Pulsar tenant associated with the sink

+
For example, to delete a sink named `cass-sink-kv` in the default namespace and public tenant, run `bin/pulsar-admin sinks delete --name cass-sink-kv --namespace default --tenant public`.

. Stop the Pulsar service:
+
[source,bash]
----
bin/pulsar-daemon stop standalone
----
+
Wait until shutdown is complete before proceeding:
+
[source,console]
----
doing stop standalone ...
stopping standalone
Shutdown is in progress... Please wait...
Shutdown is in progress... Please wait...
Shutdown completed.
----

. Remove the DataStax Pulsar connector NAR from your Pulsar `connectors` directory:
+
[source,bash]
----
rm connectors/cassandra-enhanced-pulsar-sink-1.4.0.nar
----

. Optional: Remove the connector configuration YAML file from your Pulsar `config` directory.

. Restart the Pulsar service:
+
[source,bash]
----
bin/pulsar-daemon start standalone
----