= Delete the {product}
:navtitle: Delete the {pulsar-short} connector

To completely remove the {product}, do the following:

. Delete any sinks associated with the {product-short}:
+
[source,bash,subs="+quotes"]
----
bin/pulsar-admin sinks delete --name **SINK_NAME** --namespace **SINK_NAMESPACE** --tenant **SINK_TENANT**
----
+
Replace the following:
+
* `**SINK_NAME**`: The name of the {pulsar-short} sink to delete
* `**SINK_NAMESPACE**`: The name of the {pulsar-short} namespace associated with the sink
* `**SINK_TENANT**`: The name of the {pulsar-short} tenant associated with the sink

+
For example, to delete a sink named `cass-sink-kv` in the default namespace and public tenant, run `bin/pulsar-admin sinks delete --name cass-sink-kv --namespace default --tenant public`.

. Stop the {pulsar-short} service:
+
[source,bash]
----
bin/pulsar-daemon stop standalone
----
+
Wait until shutdown is complete before proceeding:
+
[source,console]
----
doing stop standalone ...
stopping standalone
Shutdown is in progress... Please wait...
Shutdown is in progress... Please wait...
Shutdown completed.
----

. Remove the {product-short} NAR from your {pulsar-short} `connectors` directory:
+
[source,bash]
----
rm connectors/cassandra-enhanced-pulsar-sink-1.4.0.nar
----

. Optional: Remove the {product-short} configuration YAML file from your {pulsar-short} `config` directory.

. Restart the {pulsar-short} service:
+
[source,bash]
----
bin/pulsar-daemon start standalone
----