[#kafkaPause]
= Pausing the DataStax Apache Kafka Connector
:imagesdir: _images

Stops the tasks that the DataStax Apache Kafka™ Connector is running without removing the configuration from the worker.

When performing routine maintenance, pause the DataStax Connector to prevent errors and then xref:kafkaPause.adoc[resume] it once the maintenance is complete.
Pause stops the tasks that the DataStac Connector is running without removing the configuration from the worker.
To stop running tasks, use the following Kafka Connect REST API command:

----
curl -X PUT "http://worker\_ip:port/connectors/connector\_name/pause”
----

where

* worker_ip - The hostname or IP address of the Kafka Connect worker.
* port - The listening port for the Kafka Connect REST API.
By default this service runs on _port_ 8083.
* connector_name - DataStax Apache Kafka® Connector link:../configuration_reference/kafkaConnector.md#name[name].

Example - pause

----
curl -X PUT “http://localhost:8083/connectors/cassandra-sink-distributed-example/pause”
----

TIP: On success there is no output for this command.
