[#pulsarPause]
= Pausing the DataStax Apache Pulsar Connector
:imagesdir: _images

When performing routine maintenance, pause the DataStax Connector to prevent errors and then xref:opsPulsarPause.adoc[resume] it once the maintenance is complete.
Pause stops the tasks that the DataStax Connector is running without removing the configuration from the worker.
To stop running tasks, use the following Pulsar Connect REST API command:

[source,language-bash]
----
curl -X PUT "http://worker\_ip:port/connectors/connector\_name/pause”
----

where

* worker_ip - The hostname or IP address of the Pulsar Connect worker.
* port - The listening port for the Pulsar Connect REST API.
By default this service runs on _port_ 8083.
* connector_name - DataStax Apache Pulsar® Connector xref:config-reference:cfgRefPulsarConnector.adoc[name].

Example - pause

[source,language-bash]
----
curl -X PUT “http://localhost:8083/connectors/cassandra-sink-distributed-example/pause”
----

TIP: On success there is no output for this command.
