= Start the DataStax Connector in distributed mode
:imagesdir: _images

Use distributed mode with multiple workers in production environments to allow multiple instances of the DataStax Apache Pulsar™ Connector to run as a group on one or more workers.
Distributed mode automatically balances workload, allows dynamic scale up or down, and offers fault tolerance for active tasks, configuration, and offset commit data.

The DataStax Connector download package contains a sample distributed mode sample configuration file (`cassandra-sink-distributed.json.sample`).

TIP: See the Apache Pulsar documentation for https://docs.confluent.io/current/connect/userguide.html#distributed-mode[Distributed mode].

. xref:pulsarInstall.adoc[Download and install] the DataStax Apache Pulsar Connector.
. Configure the distributed worker configuration file connect-distributed.properties to fit your needs.
+
Specify the converter for the `key.converter` and `value.converter` properties that matches the form of your Pulsar data.
See link:https://docs.confluent.io/current/connect/userguide.html#configuring-converters[Configuring converters] in the Confluent documentation for more information on these properties.

. From the directory where you installed Apache Pulsar, start the distributed worker:
+
[source,language-bash]
----
bin/connect-distributed.sh config/connect-distributed.properties
----
+
The worker startup process outputs a large number of informational messages. The following message displays after the process completes:
+
[source,no-highlight]
----
[2019-10-13 19:49:25,385] INFO Finished starting connectors and tasks (org.apache.pulsar.connect.runtime.distributed.DistributedHerder:852)
----

. Register the connector configuration with the distributed worker:
+
[source,language-bash]
----
curl -X POST -H "Content-Type: application/json" -d @dse-sink.json "http://ip:port/connectors"
----
+
ip and port are the IP address and port number of the Pulsar worker.
+
Use the same port as the `rest.port` parameter set in connect-distributed.properties. The default port is 8083.
+
NOTE: You configured the dse-sink.json or dse-sink.properties file when installing the DataStax Apache Pulsar Connector.

* xref:opsPulsarStartSyntax.adoc[] Pulsar Connect REST API syntax used to create a new distributed DataStax Apache Pulsar Connector.
