= Installing DataStax Apache Pulsar(TM) Connector
:navtitle: Installation
:page-aliases: ROOT:pulsarSizing.adoc

Install DataStax Apache Pulsar(TM) Connector from the DataStax distribution tar file using an account that has write access to the Pulsar configuration directory.

The supported operating systems are Linux and macOS.

== Supported Apache Pulsar(TM) versions

The DataStax Apache Pulsar(TM) Connector requires Apache Pulsar 2.7.0 or later.

== System requirements

The system requirements for DataStax Apache Pulsar(TM) Connector depends on the workload and network capacity.
The factors include characteristics of the Pulsar topic and the cluster data models and volume.
DataStax recommends testing with realistic data flows before committing to an instance type for the connector.

DataStax Apache Pulsar(TM) Connector is bound by the amount of CPU available on the host.
The connector holds all the records pulled from Pulsar topics in memory, along with the cluster metadata and prepared statements.

Memory pressure is influenced by:

* Record size of Pulsar topics
* Number of records pulled at the same time, where the maximum is set by the workers `batchSize` parameter.
* Number of simultaneous tasks run by the connector

DataStax Apache Pulsar(TM) Connector needs adequate network capacity for the payload.
This includes the connections from Pulsar Servers to the target platform.
Scale the connector horizontally by adding additional workers to increase overall throughput.

TIP: The DataStax Apache Pulsar(TM) Connector framework automatically rebalances the load when workers are added by reallocating the tasks among the workers.

== Install the connector

Perform the following steps on a Pulsar Connect node running Apache Pulsar 2.7.0 or later:

. Download the tar file from the https://downloads.datastax.com/#apc[DataStax downloads site].
If you agree, enable the *Terms* checkbox and click the download icon.
. Extract the files:
+
[source,bash]
----
tar zxf cassandra-enhanced-pulsar-sink-1.4.0.tar.gz
----
+
The following files are unpacked into a directory such as `cassandra-enhanced-pulsar-sink-1.4.0`:
+
[source,console]
----
LICENSE.txt
README.md
THIRD-PARTY.txt
conf/example.yml
cassandra-enhanced-pulsar-sink-1.4.0.nar
----

. Create a `connectors` directory in the Pulsar home directory if it doesn't exist.
. Move the DataStax connector NAR to the Pulsar `connectors` directory:
+
[source,bash]
----
mv installation_location/cassandra-enhanced-pulsar-sink-1.4.0.nar pulsar_home/connectors
----

. Copy the sample example.yml configuration file from `cassandra-enhanced-pulsar-sink-1.4.0/conf/` to the Pulsar configuration directory, which is typically the `config` or `etc` directory.
. Update the settings as necessary.
+
IMPORTANT: If you are using the `cloud.secureConnectBundle`, *ALL* subproperties under `ssl:` must be empty.

. Ensure that the user running Pulsar has permission to access the configuration and NAR files.