= {pulsar-short} connector single instance quickstart for {dse-short}
:navtitle: Single instance quickstart for {dse-short}

This quickstart provides the minimal configuration to connect a standalone {pulsar-reg} instance to a single, standalone {dse} node.

It covers installation and configuration of {dse-short}, {pulsar}, and the connector.
Then, it demonstrates how to send simple key/value pair messages from {pulsar-short} to {dse-short} with the {pulsar-short} client utility and verify that the records were written to the database table.

== Install {dse-short}

. If you don't have {dse-short} installed already, xref:dse:installing:tarball-dse.adoc[install the tarball distribution of {dse-short}].

. Enable authentication or get the credentials for your {dse-short} cluster.
+
By default, {dse-short} doesn't enable authentication.
While this may be acceptable for this quickstart, {company} recommends enabling authentication for production clusters.

. Start {dse-short} from the installation directory:
+
[source,bash]
----
bin/dse cassandra
----
+
You can run `bin/nodetool status` to verify that {dse-short} is running from the installation directory, and get the node address and other connection details.

. Create a keyspace and table for your {pulsar-short} records:
+
.. Start `cqlsh`:
+
[source,bash]
----
bin/cqlsh
----

.. Create a keyspace named `pulsar_qs`:
+
[source,cql]
----
cqlsh> CREATE KEYSPACE IF NOT EXISTS pulsar_qs
WITH replication = {
  'class' : 'SimpleStrategy',
  'replication_factor' : 1
};
----

.. Create a table named `pulsar_kv`:
+
[source,cql]
----
cqlsh> CREATE TABLE pulsar_qs.pulsar_kv (
	key text PRIMARY KEY,
	content text
);
----

== Install {pulsar} and the connector

. Download {pulsar} 2.7.0 or later:
+
[source,bash]
----
wget https://archive.apache.org/dist/pulsar/pulsar-2.7.0/apache-pulsar-2.7.0-bin.tar.gz
----

. Untar the {pulsar-short} binary:
+
[source,bash]
----
tar xvfz apache-pulsar-2.7.0-bin.tar.gz
----

. Download the {product} tar file from the https://downloads.datastax.com/#apc[{company} downloads site].
+
For more information about system requirements for the connector, see xref:ROOT:pulsarInstall.adoc[].

. Extract the files, replacing **VERSION** with the version number of the tar file you downloaded:
+
[source,bash,subs="+quotes"]
----
tar zxf cassandra-enhanced-pulsar-sink-**VERSION**.tar.gz
----

. In your {pulsar-short} `home` directory, find the `connectors` directory.
If there isn't a `connectors` directory, create one.

. Move the {product} NAR file to the {pulsar-short} `connectors` directory:
+
[source,bash]
----
mv installation_location/cassandra-enhanced-pulsar-sink-1.4.0.nar pulsar_home/connectors
----

. In your {pulsar-short} `config` directory, create a `qs.yml` file with the following contents:
+
.qs.yml
[source,yaml]
----
configs:
  verbose: false
  batchSize: 3000
  batchFlushTimeoutMs: 1000
  topics: example_topic
  contactPoints: localhost
  loadBalancing.localDc: Cassandra
  port: 9042
  cloud.secureConnectBundle:
  ignoreErrors: None
  maxConcurrentRequests: 500
  maxNumberOfRecordsInBatch: 32
  queryExecutionTimeout: 30
  connectionPoolLocalSize: 4
  jmx: true
  compression: None
  auth:
    provider: None
    username:
    password:
    gssapi:
      keyTab:
      principal:
      service: dse
  ssl:
    provider: None
    hostnameValidation: true
    keystore:
      password:
      path:
    openssl:
      keyCertChain:
      privateKey:
    truststore:
      password:
      path:
    cipherSuites:
  topic:
    example_topic:
      pulsar_qs:
        pulsar_kv:
          mapping: 'key=key,content=value'
          consistencyLevel: LOCAL_ONE
          ttl: -1
          ttlTimeUnit : SECONDS
          timestampTimeUnit : MICROSECONDS
          nullToUnset: true
          deletesEnabled: true
      codec:
        locale: en_US
        timeZone: UTC
        timestamp: CQL_TIMESTAMP
        date: ISO_LOCAL_DATE
        time: ISO_LOCAL_TIME
        unit: MILLISECONDS
----

. If your cluster has authentication enabled, you want to use an SSL-encrypted connection, or your cluster isn't compatible with the connection properties in `qs.yml`, you must edit the configuration file as explained in xref:ROOT:cfgRefPulsarDseConnection.adoc[].

. Ensure that the user running {pulsar-short} has permission to access the configuration and NAR files.

== Run {pulsar-short} with the connector

. Start {pulsar} in standalone mode:
+
[source,bash]
----
bin/pulsar standalone
----

. In a new terminal, check that the {product} is running:
+
[source,bash]
----
curl -s http://localhost:8080/admin/v2/functions/connectors
----
+
Make sure the response includes the {product}:
+
[source,json]
----
[{"name":"cassandra-enhanced","description":"A DataStax {pulsar-short} Sink to load records from {pulsar-short} topics to {cass-reg} or DataStax Enterprise(DSE)\n","sinkClass":"com.datastax.oss.sink.pulsar.RecordCassandraSinkTask"}]
----

. Create a {pulsar-short} sink:
+
[source,bash]
----
bin/pulsar-admin sinks create \
	--name dse-sink-kv \
	--classname com.datastax.oss.sink.pulsar.StringCassandraSinkTask \
	--sink-config-file config/qs.yml \
	--sink-type cassandra-enhanced \
	--tenant public \
	--namespace default \
	--inputs "persistent://public/default/example_topic"
----
+
The topic name and mapping are set in the connector configuration YAML file.

. Send some messages to your new sink:
+
[source,bash]
----
bin/pulsar-client produce -k "Message 1" -m "Content 1" persistent://public/default/example_topic
bin/pulsar-client produce -k "Message 2" -m "Content 2" persistent://public/default/example_topic
bin/pulsar-client produce -k "Message 3" -m "Content 3" persistent://public/default/example_topic
----

. To verify that the messages were written to {dse-short}, start `cqlsh`, and then query your `pulsar_kv` table:
+
[source,cql]
----
cqlsh> SELECT * FROM pulsar_qs.pulsar_kv;
----
+
The result should include the test messages you sent:
+
[source,console]
----
 key       | content
-----------+-----------
 Message 3 | Content 3
 Message 2 | Content 2
 Message 1 | Content 1

(3 rows)
----

== Next steps

Your schemas probably require more complex mappings than the example used in this quickstart.
Explore the following documentation to get started with more complex mappings and schemas:

* xref:cfgPulsarDisplayingTopic.adoc[Print messages] to determine the data structure of the topic messages.

* Create xref:cfgPulsarMapKeyPair.adoc[key-value pair mappings], xref:cfgPulsarMapJson.adoc[JSON mappings], and xref:cfgPulsarMapAvroMessages.adoc[Avro mappings].

* Try advanced and specialized mapping functionality, such as xref:cfgPulsarMapUdt.adoc[mapping UDTs].

* Use one connector instance to xref:cfgPulsarMapMultipleTables.adoc[ingest a single topic into multiple tables] or xref:cfgPulsarMultTopicToTables.adoc[ingest multiple topics to different tables].