[#_installing_datastax_apache_kafka_connector_1_4_0_kafkainstall_task]
= Installing DataStax Apache Kafka Connector 1.4.0
:imagesdir: _images

Install on Linux-based platform using a binary tarball.

Install DataStax Apache Kafka™ Connector 1.4.0 from the DataStax distribution tar file using an account that has write access to the Kafka configuration directory.

The supported operating systems are Linux and macOS.

[#_supported_apache_kafka_versions_kafkasupportedversions_section]
== Supported Apache Kafka versions

Install the DataStax Apache Kafka® Connector on any of following versions:

* Confluent 3.2 and higher
* Apache Kafka 0.10.2 and higher

. IMPORTANT: https://www.apache.org/licenses/LICENSE-2.0[Apache-2.0 license agreement].
By downloading this DataStax product, you agree to the terms of the open-source Apache-2.0 license agreement.
+
Perform the following steps on a Kafka Connect node:

. Download the tar file from the https://downloads.datastax.com/#akc[DataStax downloads site].
If you agree, enable the *Terms* checkbox and click the download icon.
. Extract the files:

....
```language-bash
tar zxf kafka-connect-cassandra-sink-1.4.0.tar.gz
```

The following files are unpacked into a directory such as `kafka-connect-cassandra-sink-1.4.0`.

```no-highlight
LICENSE.txt
README.md
THIRD-PARTY.txt
conf/cassandra-sink-distributed.json.sample
conf/cassandra-sink-standalone.properties.sample
kafka-connect-cassandra-sink-1.4.0.jar
```
....

. Configured the DataStax connector JAR using one of the following methods:      -   Move the DataStax connector JAR to the Kafka plugins directory:
+
[source,language-bash]
----
   mv installation\_location/kafka-connect-cassandra-sink-1.4.0.jar kafka\_plugins\_dir
----

....
-   Configure the path to the JAR:

    Apache Kafka 0.11.x and later - Specify the JAR location in the `plugin.path` parameter in the `connect-standalone.properties` or `connect-distributed.properties` file that is passed to the worker start-up scripts. Example:

    ```no-highlight
    plugin.path=install\_location/kafka-connect-cassandra-sink-1.4.0.jar
    ```

    **Note:** Confluent 3.3 and later are supported.
....

. Copy the sample configuration file from `kafka-connect-cassandra-sink-1.4.0/conf/` to the Kafka configuration directory, which is typically the `config` or etc directory.

....
DataStax provides the following sample files in the conf directory of the connector distribution package:

-   cassandra-sink-standalone.properties.sample for standalone mode. It is a Java properties file that contains all settings with descriptions. Settings with a default value are commented out.
-   cassandra-sink-distributed.json.sample for distributed mode. This file is in JSON format and contains all settings, which are enumerated and active. To use the default values, remove settings from the configuration file. JSON does not support comments. 6.   Rename the sample file to cassandra-sink.properties or cassandra-sink.json.

**Attention:** If you will use DataStax Apache Kafka™ Connector to stream records with a DataStax Astra cloud database, refer to the Astra documentation for information about specifying the [secure connect bundle](../../dscloud/astra/dscloudStartKafka.md) in the distributed cassandra-sink.json file. The secure connect bundle ZIP \(downloaded via the Astra console\) contains the security certificates and credentials for your Astra database.
....

. Update the settings as necessary.
See link:/en/kafka/doc/kafka/kafkaConfigTasksTOC.html[Configuring the DataStax Apache Kafka Connector].
. Ensure that the user running Kafka has permission to access the configuration and JAR files.
. Next, refer to the DataStax Apache Kafka Connector link:/en/kafka/doc/kafka/kafkaIntro.html[introduction].
