= Install {product}
:navtitle: Install
:page-aliases: ROOT:pulsarSizing.adoc

Install {product} from the {company} distribution tar file using an account that has write access to the {pulsar-short} configuration directory.

== System requirements

The system requirements for {product-short} depends on the workload and network capacity.
The factors include characteristics of the {pulsar-short} topic and the cluster data models and volume.
{company} recommends testing with realistic data flows before committing to an instance type for the {product-short}.

Database::
The {product-short} supports the following databases:
+
* {company} {astra-db}
* {dse} 4.7 and later (non-EOL versions recommended)
* Open source {cass-reg} 2.1 and later (non-EOL versions recommended, full compatibility with 5.x isn't guaranteed)

{pulsar-short}::
The {product-short} requires {pulsar} 2.7.0 or later.
+
The {product-short} supports the following data structures in {pulsar-short} topics:
+
* Primitive string values
* Avro
* JSON formatted string with JSON schema
* JSON formatted string inside a schemaless topic

Operating system::
The supported operating systems are Linux and macOS.

CPU::
{product-short} is bound by the amount of CPU available on the host.
The {product-short} holds all the records pulled from {pulsar-short} topics in memory, along with the cluster metadata and prepared statements.
+
Memory pressure is influenced by the following:
+
* Record size of {pulsar-short} topics
* Number of records pulled at the same time, where the maximum is set by the workers `batchSize` parameter.
* Number of simultaneous tasks run by the {product-short}

Network::
{product-short} needs adequate network capacity for the payload.
This includes the connections from {pulsar-short} Servers to the target platform.
Scale the {product-short} horizontally by adding additional workers to increase overall throughput.
+
The {product-short} framework automatically rebalances the load when workers are added by reallocating the tasks among the workers.

== Install the {product-short}

Perform the following steps on a {pulsar-short} Connect node running {pulsar} 2.7.0 or later.
If you need to install {pulsar-short}, see xref:ROOT:pulsarQuickStart.adoc[].

. Download the {product-short} tar file from the https://downloads.datastax.com/#apc[{company} downloads site].

. Extract the files, replacing **VERSION** with the version number of the tar file you downloaded:
+
[source,bash,subs="+quotes"]
----
tar zxf cassandra-enhanced-pulsar-sink-**VERSION**.tar.gz
----
+
The following files are unpacked into a directory named after the tar file, such as `cassandra-enhanced-pulsar-sink-1.4.0`:
+
[source,console]
----
LICENSE.txt
README.md
THIRD-PARTY.txt
conf/example.yml
cassandra-enhanced-pulsar-sink-1.4.0.nar
----

. In your {pulsar-short} `home` directory, find the `connectors` directory.
If there isn't a `connectors` directory, create one.

. Move the {product-short} NAR file to the {pulsar-short} `connectors` directory:
+
[source,bash]
----
mv installation_location/cassandra-enhanced-pulsar-sink-1.4.0.nar pulsar_home/connectors
----

. Copy the sample configuration file `example.yml` from `cassandra-enhanced-pulsar-sink-**VERSION**/conf/` to your {pulsar-short} `config` directory.
+
If you plan to create multiple sinks from this connector, give your configuration file a unique name.

. Edit the configuration file as necessary using the information provided in this documentation.
For example, for information about connection, authentication, and encryption parameters, see xref:ROOT:cfgRefPulsarDseConnection.adoc[].

. Ensure that the user running {pulsar-short} has permission to access the configuration and NAR files.

== Start {pulsar-short} with the {product-short}

. Start, restart, or reload your {pulsar-short} instance:
+
[source,bash]
----
bin/pulsar-admin sinks reload
----

. Check that the {product-short} is available:
+
[source,bash]
----
bin/pulsar-admin sinks available-sinks
----

. Create a {pulsar-short} sink:
+
[source,bash,subs="+quotes"]
----
bin/pulsar-admin sinks create \
	--name **SINK_NAME** \
	--classname com.datastax.oss.sink.pulsar.StringCassandraSinkTask \
	--sink-config-file config/example.yml \
	--sink-type cassandra-enhanced \
	--tenant **TENANT_NAME** \
	--namespace **NAMESPACE_NAME** \
	--inputs "persistent://**TENANT_NAME**/**NAMESPACE_NAME**/**TOPIC_NAME**"
----
+
Replace the following:
+
* **`SINK_NAME`**: A unique name for the sink.
* **`TENANT_NAME`**: The name of the relevant {pulsar-short} tenant.
* **`NAMESPACE_NAME`**: The name of the relevant {pulsar-short} namespace.
* **`TOPIC_NAME`**: The name of the {pulsar-short} topic that you want to stream to your database.
+
The topic mapping is set in the {product-short}'s configuration YAML file.
Make sure that it matches the schema of the table where you want to write the messages.
For more information, see xref:ROOT:cfgRefPulsarDseTable.adoc[].

. Use `pulsar-client produce` to https://pulsar.apache.org/docs/2.11.x/concepts-messaging/[send some messages] to your new sink, and then use `cqlsh` to verify that the messages were written to the table in your database.

== Next steps

Explore the rest of the documentation to learn more about configuring and using the {product-short}.