[#_using_a_kerberos_ticket_cache_to_authenticate_connector_running_on_a_stand_alone_worker_kafkakerberosticket_task]
= Using a Kerberos ticket cache to authenticate connector running on a stand-alone worker
:imagesdir: _images

Authenticate the DataStax Connector session using a Kerberos ticket with a worker that is running in stand-alone mode.

Authenticate the DataStax Apache Kafka™ Connector session using a Kerberos ticket with a worker that is running in stand-alone mode.

. Put the Kerberos configuration file (xref:../../glossary/gloss_krb5conf.adoc[krb5.conf]) in /etc.

 **Tip:** To use an alternate location for the configuration file \(other than the default location `/etc`\), set the environment variable to point to the configuration file. See [Using an alternate location for the Kerberos files](kafkaKerberosConfigFile.md).

. Add accounts to Kerberos and the cluster:      1.
Add a service principal for the host where the connector is running in standalone mode.
See http://web.mit.edu/kerberos/krb5-current/doc/admin/database.html?highlight=add%20principal#adding-modifying-and-deleting-principals[Add principal].
2.
Add a login-role.
See link:/en/dse/6.7/dse-admin/datastax_enterprise/security/Auth/secKerberosRole.html[Adding roles for Kerberos principals].
3.
Allow write access to the tables by granting `MODIFY` permission on the table to the login role.
See link:/en/dse/6.7/dse-admin/datastax_enterprise/security/secDataPermission.html[Controlling access to keyspaces and tables].
. Configure the connector as described in xref:../kafkaConfigTasksTOC.adoc[Configuring the DataStax Apache Kafka Connector] using xref:../configuration_reference/kafkaKerberos.adoc[Kerberos authentication] parameters.
. Get a Kerberos ticket by running `kinit` with the DataStax Apache Kafka Connector principal:

 ```language-bash
 kinit datastaxconnector/kafka@EXAMPLE.COM
 ```

. Start the DataStax Apache Kafka Connector.
See xref:../operations/kafkaStartStandalone.adoc[Deploying the DataStax Connector in standalone mode].
