= Authentication and encryption
:page-aliases: ROOT:cfgRefPulsarAuthLdap.adoc, ROOT:cfgRefPulsarAuth.adoc, ROOT:cfgRefPulsarConnector.adoc, ROOT:cfgRefPulsarSsl.adoc

You can authenticate the DataStax Apache Pulsar(TM) Connector session using internal, LDAP, Kerberos, or application token authentication, depending on the methods supported by your cluster.
The connector also supports SSL-encrypted connections.

[tabs]
======
DSE::
+
--
When xref:6.9@dse:securing:authorization-authentication/enable-unifiedi-authentication.adoc[DSE Unified Authentication is enabled], you must provide internal/LDAP authentication credentials or the Kerberos keytab filepath in the <<authentication-parameters,authentication parameters>>.
The connector supports DSE role management with internal and LDAP schemes.

If the cluster has client encryption enabled, configure the <<ssl-encrypted-connections,SSL keys and certificates in the Pulsar Connector>>.
SSL encryption settings are configured in the xref:6.9@dse:securing:encrypt-client-node-ssl.adoc[DSE client-to-node encryption options].

For information about authentication configuration for DSE clusters, see the documentation for your version of DSE.
--

Astra::
+
--
To connect to Astra, provide the application token credentials in the <<authentication-parameters,authentication parameters>>, and use the Secure Connect Bundle (SCB) to establish an <<ssl-encrypted-connections,SSL-encrypted connection>>.
--
======

[#authentication-parameters]
== Authentication parameters

If the cluster has internal or LDAP authentication enabled, configure the username and password settings for the Pulsar Connector.
You must also provide a login role for the connector with access to the mapped tables.

In your connector's configuration YAML file, set the relevant auth parameters for `auth.provider`, `auth.username`, and `auth.password`:

[source,yaml]
----
auth:
  provider: DSE
  username: login_role
  password: password
----

provider::
Select the type of authentication provider configured for the cluster:
+
* **`None` (default)**: No authentication
* **`DSE`**: Internal or LDAP authentication
* **`GSSAPI`**: SASL authentication to DSE clusters using the GSSAPI mechanism (Kerberos authentication)
+
When using GSSAPI, you must provide the path to the Kerberos configuration file (`krb5.conf`) in the `java.security.krb5.conf` system property at startup.
For more information, see xref:ROOT:ecPulsarInternalLdapAuth.adoc[].

username::
For DSE, provide the login role name or LDAP username.
If xref:6.9@dse:managing:configure/configure-dse-yaml.adoc#authorizationOptions[authorization is enabled], the DataStax connector login role must have a minimum of `modify` privileges on tables receiving data from the DataStax Apache Pulsar(TM) Connector.
+
For Astra, enter the literal string `token` or provide the `clientId` from an Astra application token.

password::
For DSE, provide the login role or LDAP password.
+
For Astra, provide a secure reference to your Astra application token, or provide the `clientSecret` from an application token.

[#ssl-encrypted-connections]
== SSL-encrypted connections

[tabs]
======
DSE::
+
--
For DSE clusters with client-to-node encryption enabled, configure the `ssl:` properties for the Pulsar Connector:

[source,yaml]
----
ssl:
  provider:
  cipherSuites:
  hostnameValidation: true
  keystore:
    password:
    path:
  truststore:
    password:
    path:
  openssl:
    keyCertChain:
    privateKey:
----

provider::
SSL provider to use:
+
* `None` (default)
* `JDK`
* `OpenSSL`

cipherSuites::
Cipher suites to enable
+
Default: unset (no cipher suites)

hostnameValidation::
Whether to validate node hostnames when using SSL
+
Default: `true` (enabled)

keystore::
+
* `password`: Keystore password
* `path`: Path to the keystore file

truststore::
+
* `password`: Truststore password
* `path`: Path to the truststore file

openssl::
Only applicable when using OpenSSL
+
* `keyCertChain`: Path to the SSL certificate file
* `privateKey`: Path to the private key file

[TIP]
====
In your Pulsar configuration, you can provide paths to the keystore, truststore, private key, and certificate files, or you can provide the files as base64-encoded strings:

. Encode the file:
+
[source,bash]
----
base64 -i trust-store-key
----

. Set the resulting Base64-encoded string in the appropriate parameter:

[source,yaml]
----
  path: base64:UEsDBBQACAAIADmJJ...
----

The Pulsar function framework handles deployment to additional Pulsar machines.
====
--

Astra::
+
--
When connecting to Astra, use your database's Secure Connect Bundle (SCB) zip file to establish an SSL-encrypted connection.
The SCB also sets the local datacenter for the connection.

[tabs]
====
Unencrypted string::
+
Provide the full path to the SCB zip file directly in `cloud.secureConnectBundle`:
+
[source,yaml]
----
cloud.secureConnectBundle=/path/to/sbc.zip
----

Base64-encoded string::
+
You can provide the literal path to your SCB or encode the zip file using the standard base64 tool:
+
[source,bash]
----
base64 -i scb.zip
----
+
Then, set the resulting base64-encoded string directly in the Pulsar configuration file:
+
[source,yaml]
----
cloud.secureConnectBundle=base64:UEsDBBQACAAI....
----
+
The Pulsar function framework handles deployment to additional Pulsar machines.
====

You must also provide set `auth.username` and `auth.password`, as explained in <<authentication-parameters>>.

When using `cloud.secureConnectBundle`, _all_ subproperties of `ssl:` must be empty.
These properties are managed by the SCB.
--
======