[#_using_a_kerberos_ticket_cache_to_authenticate_connector_running_on_a_stand_alone_worker_pulsarkerberosticket_task]
= Using a Kerberos ticket cache to authenticate connector running on a stand-alone worker
:imagesdir: _images

Authenticate the DataStax Apache Pulsar™ Connector session using a Kerberos ticket with a worker that is running in stand-alone mode.

. Put the Kerberos configuration file `krb5.conf` in `/etc`.
+
TIP: To use an alternate location for the configuration file (other than the default location `/etc`), set the environment variable to point to the configuration file. See [Using an alternate location for the Kerberos files](pulsarKerberosConfigFile.md).

. Add accounts to Kerberos and the cluster:      
. Add a service principal for the host where the connector is running in standalone mode.
See http://web.mit.edu/kerberos/krb5-current/doc/admin/database.html?highlight=add%20principal#adding-modifying-and-deleting-principals[Add principal].
. Add a login-role.
See link:https://docs.datastax.com/en/dse/6.8/dse-admin/datastax_enterprise/security/Auth/secKerberosRole.html[Adding roles for Kerberos principals].
. Allow write access to the tables by granting `MODIFY` permission on the table to the login role.
See link:https://docs.datastax.com/en/dse/6.8/dse-admin/datastax_enterprise/security/secDataPermission.html[Controlling access to keyspaces and tables].
. Configure the connector using xref:config-reference:cfgRefPulsarKerberos.adoc[Kerberos authentication] parameters.
. Get a Kerberos ticket by running `kinit` with the DataStax Apache Pulsar Connector principal:
+
[source,language-bash]
----
kinit datastaxconnector/pulsar@EXAMPLE.COM
----

. Start the DataStax Apache Pulsar Connector. See xref:opsPulsarStartStandalone.adoc[].
