[#_using_an_alternate_location_for_the_kerberos_files_kafkakerberosconfigfile_task]
= Using an alternate location for the Kerberos files
:imagesdir: _images

When using a location other than /etc for the `krb5.conf` file, add the custom path to Kafka Connect and Kerberos environment variables.

When using a location other than /etc for the xref:../../glossary/gloss_krb5conf.adoc[krb5.conf] file, add the custom path to Kafka Connect and Kerberos environment variables.
If the Kerberos configuration file is not available on the system, get it from the Kerberos system administrator.

TIP: See http://web.mit.edu/kerberos/krb5-current/doc/mitK5defaults.html#paths[Default paths].

* Kerberos clients
* Configure the path to file for Kerberos clients, such as `kinit`, `klist`, and `kdestroy`.
Set the path to the file in the `KRB5_CONFIG` environment variable:

 ```language-bash
 export KRB5_CONFIG="path_to_file"
 ```

* Kafka Connect framework
* Configure the path to the file for the DataStax Apache Kafka Connector.

....
Add the system property, `java.security.krb5.conf`, to the `KAFKA_OPTS` environment variable:

```language-bash
export KAFKA_OPTS=$KAFKA_OPTS -Djava.security.krb5.conf="path_to_file"
```

**Note:** Both `connect-standalone` and `connect-distributed` support specifying extra JVM options through the `KAFKA_OPTS` environment variable.
....
