= Authentication
:page-aliases: ROOT:cfgRefPulsarAuthLdap.adoc, ROOT:cfgRefPulsarAuth.adoc

Authenticate the DataStax Apache Pulsar(TM) Connector session using internal, LDAP, or Kerberos authentication, depending on the methods supported by your cluster.

== Use the Pulsar Connector with DSE authentication

When xref:6.9@dse:securing:authorization-authentication/enable-unifiedi-authentication.adoc[DSE Unified Authentication is enabled], you must provide credentials for internal/LDAP authentication or provide the location of the Kerberos keytab file.

The connector also supports DSE role management with internal and LDAP schemes.

For information about authentication configuration for DSE clusters, see the documentation for your version of DSE.

== Internal or LDAP authentication

If the cluster has internal or LDAP authentication enabled, configure the username and password settings for the Pulsar Connector.
You must also provide a login role for the connector with access to the mapped tables.

Set the relevant auth parameters in dse.yaml for `auth.provider`, `auth.username` (the login role name or LDAP username), and `auth.password`.

[source,yaml]
----
auth:
  provider: DSE
  username: login_role
  password: password
----

provider::
Select the type of authentication provider configured for the cluster:
+
* **`None` (default)**: No authentication
* **`DSE`**: Internal or LDAP authentication
* **`GSSAPI`**: SASL authentication to DSE clusters using the GSSAPI mechanism (Kerberos authentication)
+
When using GSSAPI, you must provide the path to the Kerberos configuration file (`krb5.conf`) in the `java.security.krb5.conf` system property at startup.
For more information, see xref:ROOT:ecPulsarInternalLdapAuth.adoc[].

username::
For DSE, provide the login role name or LDAP username.
If xref:6.9@dse:managing:configure/configure-dse-yaml.adoc#authorizationOptions[authorization is enabled], the DataStax connector login role must have a minimum of `modify` privileges on tables receiving data from the DataStax Apache Pulsar(TM) Connector.
+
For Astra, enter the literal string `token` or provide the `clientId` from an Astra application token.

password::
For DSE, provide the login role or LDAP password.
+
For Astra, provide a secure reference to your Astra application token, or provide the `clientSecret` from an application token.