[#_using_the_datastax_apache_kafka_connector_with_kerberos_kafkakerberosauth_concept]
= Using the DataStax Apache Kafka Connector with Kerberos
:imagesdir: _images

Authenticate the DataStax Apache Kafka Connector session using Kerberos.

When connecting to a cluster that has Kerberos enabled, set up the following:

* Service accounts:
 ** *Kerberos principal* - Service account used by the connector to start a session with the cluster.
See https://web.mit.edu/kerberos/krb5-latest/doc/admin/database.html#principals[Principals].
 ** *Database log-in role* Role that matches the Kerberos principal name (case-sensative) with login set to `true`.
See link:/en/dse/6.7/dse-admin/datastax_enterprise/security/Auth/secKerberosRole.html[Adding roles for Kerberos principals].
+
NOTE: When authorization is also enabled, the role must have modify permissions on all tables mapped to a Kafka topic.
See link:/en/dse/6.7/dse-admin/datastax_enterprise/security/secDataPermission.html[Controlling access to keyspaces and tables].
* On the *Kafka Connect* nodes:
 ** Install `kinit`.
This utility obtains and caches Kerberos tickets used for authentication.
See https://web.mit.edu/kerberos/krb5-latest/doc/admin/install_clients.html[*Installing and configuring UNIX client machines*].
 ** Setup krb5.conf, which identifies the KDS (key distribution server), Kerberos administration server, and contains other settings.
Required for Kerberos client tools, such as `kinit`.
See https://web.mit.edu/kerberos/krb5-latest/doc/admin/install_clients.html#client-machine-configuration-files[*Client machine configuration files*].
 ** Create a keytab file.
A keytab file contains a certificate that allows the connector to obtain credentials without re-entering the password each time it initiates session with the cluster.
 ** Set Kerberos parameters in the DataStax Connector configuration file.
* *xref:../../kafka/security/kafkaKerberosConfigFile.adoc[Using an alternate location for the Kerberos files]* + When using a location other than /etc for the `krb5.conf` file, add the custom path to Kafka Connect and Kerberos environment variables.
* *xref:../../kafka/security/kafkaKerberosTicket.adoc[Using a Kerberos ticket cache to authenticate connector running on a stand-alone worker]* + Authenticate the DataStax Connector session using a Kerberos ticket with a worker that is running in stand-alone mode.
