= About your Astra database
:slug: about-your-astra-database

Welcome! Let's cover some basics and review how you can get connected.

Your paid database starts the following specifications:
* A single region
* A single keyspace
* Storage based on your xref:service-tier-options.adoc[service tier]
* Capacity for up to 200 tables
* Replication factor of three to provide optimal uptime and data integrity
* One capacity unit (CU), which represents three database instances grouped together

[NOTE]
====
If you choose the Free tier, then your database has a 5 GB capacity so you can test Astra and start developing today.
Free tier databases also have a replication factor of one.
====

You can later xref:resizing-databases[resize the database] to increase the number of CUs

To better understand your database capabilities, review the xref:datastax-astra-database-limits[DataStax Astra database limits].

== No configuration necessary
Cassandra Query Language (CQL) is the primary language for communicating with your Astra database.
Use CQL to insert, update, and query data in tables, drop tables, and much more.
Like SQL, CQL statements change data, look up data, store data, or change the way data is stored.
If you're new to CQL, see the DataStax documentation for understanding the https://docs.datastax.com/en/astra-cql/doc/cql/cql/cql_using/cqlSyntax.html[CQL command syntax].

== How do you want to connect?
When your database is active, it's time to get xref:connecting-to-database[connected].
There are multiple ways to connect to your database, depending on your familiarity with CQL and how you want to connect.

[cols=2*,options=header]
|===
|Options
|Description

|I don't know CQL, but want to use my database now.
|Use the integrated CQLSH console or the xref:connecting-to-astra-databases-using-cqlsh[Connecting to Astra databases using CQLSH] standalone CQLSH tool to interact with your database using CQL.

|I know some CQL and want to connect quickly to use my database.
|Programming Language

|I have an application and want to use the DataStax drivers.
|Initialize one of the xref:connecting-to-astra-databases-using-datastax-drivers[DataStax drivers] to manage database connections for your application.

|===
