= What is DataStax Astra?
:slug: what-is-datastax-astra

https://astra.datastax.com[DataStax Astra], built on the best distribution of Apache Cassandra™, provides the ability to develop and deploy data-driven applications with a cloud-native service, without the hassles of database and infrastructure administration.

By automating tuning and configuration, DataStax Astra radically simplifies database operations.

xref:datastax-astra-database-limits.adoc[Limits] help enforce best practices by defining parameters for operations, such as table number and column size limits, ensuring the database operates with consistent performance and maintains cluster health.

Each Astra database on a paid tier employs a single capacity unit (CU) by default, which represents three database instances that are grouped together. A single CU represents three replicas. CUs ensure high availability by implementing a consistent replication factor that is acceptable for development and production workloads.

To ensure that an Astra database doesn't exceed capacity, you can xref:resizing-databases.adoc[expand the database] by adding CUs.

Developers can easily xref:resizing-databases.adoc[resize resources] as their needs grow and change and xref:parking-databases.adoc[park databases] when not in use to save costs and pay for only storage.

For more information about DataStax Astra, see xref:datastax-astra-faq.adoc[DataStax Astra FAQ].
