[#_kafka_topic_to_table_settings_kafkacassandratable_reference]
= Kafka topic-to-table settings {#kafkaCassandraTable .reference}
:imagesdir: _images

Capture Kafka topics in the supported database by specifying a target keyspace, table, and then map the topic fields to table columns.

Capture Kafka topics in the link:../kafkaIntro.md#kafkaIntroduction[supported database] by specifying a target keyspace, table, and then map the topic fields to table columns in the name of the parameter.

[#_parameters_synopsis_section]
== Parameters {#synopsis .section}

Use the following syntax for standalone properties file:

[source,no-highlight]
----
topics=topic\_list
prefix.mapping=mapping\_specification
prefix.consistencyLevel=WRITE\_CONSISTENCY\_LEVEL
prefix.ttl=seconds
prefix.nullToUnset=true
prefix.deletesEnabled=true
----

topics:: A comma separated list of all topics to which the DataStax Connector subscribes.

prefix::
Defines the topic-to-table to which the parameters apply.
This allows records from a single topic to be ingested into multiple database tables.
Define the parameter prefix using the following syntax:

[source,no-highlight]
----
topic.topic\_name.keyspace\_name.table\_name
----

where:

* topic_name - Kafka topic name.
* keyspace_name - database keyspace where the table is located.
* table_name - database table where data is written.

mapping::
Required, field-to-column mapping.
See xref:../kafkaMapTopicTable.adoc[Mapping kafka topics to database tables].

consistencyLevel::
Query consistency level.
DSE settings are:

....
-   [ALL](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__all)
-   [EACH QUORUM](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__each_quorum)
-   [QUORUM](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__quorum)
-   [LOCAL\_QUORUM](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__local_quorum)
-   [ONE](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__one)
-   [TWO](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__two)
-   [THREE](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__three)
-   [LOCAL\_ONE](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__local_one) \(default\)
-   [ANY](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html#dbIntConfigConsistency__any)

See [How are consistent read and write operations handled?](/en/dse/6.7/dse-arch/datastax_enterprise/dbInternals/dbIntAboutDataConsistency.html)

Default: `LOCAL_ONE`
....

nullToUnset::
Whether to treat nulls in Kafka as UNSET in DSE.
DataStax recommends using the default to avoid creating unnecessary tombstones.

 Default: `true`

ttl::
Time-to-live.
Set to the number of seconds before the data is automatically deleted from the DSE table.
When you configure `topic.<topic-name>.<keyspace-name>.<table-name>.ttl`, all rows for that topic table will have this same `TTL` value.
DataStax Kafka Connector appends `AND TTL <configured-ttl-value>` to the INSERT statement for those rows.

 Default: `-1` \( disabled \)

deletesEnabled:: When enabled, treat records that after mapping would result in only non-null values for primary key columns as deletes, rather than inserting/updating nulls for all regular columns.

NOTE: Only triggers if the setting is enabled and the mapping specification contains all DSE table columns.

 Default: `true`

*Parent topic:* xref:../../kafka/kafkaConfigToc.adoc[DataStax Apache Kafka Connector configuration parameter reference]
