= DataStax Developer Studio for Astra
:slug: connecting-to-databases-with-datastax-developer-studio

You can use DataStax Developer Studio to interact with Astra databases created using https://astra.datastax.com[DataStax Astra].

When creating an Astra database, an embedded Studio instance is automatically configured for interactive CQL commands.
Each notebook in Studio has only one connection, but a connection can serve multiple notebooks.

== Limitations
When using Studio with an Astra database, the following limitations apply:
* Each Astra database includes a Studio instance that works only with that database.
* Only the database owner can access the integrated Studio. To share notebooks, you must export them for your teammates to upload.
* Because each Astra database operates using a single keyspace, you cannot create additional keyspaces using Studio.

== Prerequisite
xref:creating-your-astra-database.adoc[Create a database] using [DataStax Astra](https://astra.datastax.com).

== Procedure
. Open a browser, navigate to [DataStax Astra](https://astra.datastax.com/), and log in.
. From your **Dashboard** page, select your database.
. On the **Summary** page, select **Studio**. A DataStax Developer Studio instance that is connected to your Cassandra database opens.
. When prompted, enter the username and password used when creating your database through the DataStax Astra console.
. Click **Save** to save the credentials.

== Results
You can now interact with your Astra database using Studio.
Use the example notebook to create tables and rows in your keyspace.
