= Drivers for Astra
:slug: connecting-to-astra-databases-using-datastax-drivers

Use one of the following DataStax drivers to connect to your DataStax Astra database. Choose the DataStax driver for your preferred programming language.

Before using the DataStax drivers, review the https://docs.datastax.com/en/devapp/doc/devapp/driversBestPractices.html[Best practices for DataStax drivers] to understand the rules and recommendations for improving performance and minimizing resource utilization in applications that use DataStax drivers.

[TIP]
====
DataStax recommends using the unified DataStax drivers.
See this https://www.datastax.com/blog/2020/01/better-drivers-for-cassandra[blog post] for more information.
You can also use the DataStax Enterprise (DSE) drivers, which exposes the same API for connecting to Cassandra databases.
====

== Already have a DataStax driver?
xref:migrating-datastax-drivers-to-connect-to-astra-databases.adoc[Migrate your existing DataStax driver] to connect to an Astra database.
