= DataStax Node.js driver
:slug: connecting-to-your-database-with-the-datastax-nodejs-driver

Use the unified DataStax Node.js driver to connect to your DataStax Astra database and begin building your own application.

[TIP]
====
DataStax recommends using the unified DataStax Node.js driver.
If you have an existing Apache Cassandra or DataStax Enterprise (DSE) Node.js driver, xref:migrating-your-datastax-nodejs-driver-to-connect-with-astra-databases.adoc[migrate the driver] to a version that is capable of connecting to Astra databases.
====

== Prerequisites
. xref:accessing-your-database.adoc[Download the secure connect bundle] to obtain connection credentials for your DataStax Astra database.
. [Download](https://nodejs.org/en/download/) and install a current Node.js LTS version with npm.
[TIP]
====
Alternatively, xref:providing-access-to-astra-databases.adoc[have a teammate provide access to their Astra database].
====

==Procedure
. Install the DataStax Node.js driver:
```
npm install cassandra-driver
```
. Create a `connect-database.js` file in the main directory for your Node.js project.
```
cd nodejsProject\ntouch connect-database.js
```

. Copy the following connection code into the `connect-database.js` file.
[NOTE]
====
Include the absolute path to the secure connect bundle for your Cassandra database (`secure-connect-database_name.zip`) in the `secureConnectBundle` parameter, as shown in the following examples.
====

```
'use strict'\nconst { Client } = require('cassandra-driver');
```
. After the `Client` class, add the following code to `connect-database.js`.
This code creates a `Client` instance to connect to your Astra database, runs a CQL query, and prints the output to the console.
```
async function run() {
  const client = new Client({
    cloud: { secureConnectBundle: 'path/to/secure-connect-database_name.zip' },
    credentials: { username: 'username', password: 'password' }
  });

  await client.connect();

  // Execute a query
  const rs = await client.execute('SELECT * FROM system.local');
  console.log(`Hello from cluster: ${rs.first()['cluster_name']}`);

  await client.shutdown();
}

// Run the async function
run();
```

. Save and close the `connect-database.js` file.
. Run the `connect-database.js` example with the Node.js runtime:
```
node connect-database.js
```

The console output displays the _cluster_name_ value from the `system.local` table.
