= Create a notebook in DataStax Developer Studio
:slug: creating-a-notebook-in-datastax-developer-studio

Create a DataStax Developer Studio notebook that contains text and runnable code. Because Developer Studio is already connected to your DataStax Astra database, creating a notebook requires only adding a name to get started.

== Prerequisite
link:doc:creating-your-astra-database[Create an Astra database], which includes an embedded Developer Studio instance that is automatically configured for interactive CQL commands.

== Procedure
. Click the plus (*+*) icon to add a notebook. The *Create Notebook* dialog displays.
 . Enter a name for the notebook.
 . Select your registered email from the *Connection* dropdown list.
 . Click *Create*.
The notebook opens with a single empty (default) cell in CQL edit mode.
This mode can be set to CQL or Markdown.

The following steps show a Markdown example:
. In the default cell, change the dropdown to *Markdown*.
. Add some verbiage to the default cell:
```
My Notebook
-----------
Schema-aware content-assist improves productivity.
Studio inspects your schema to make smart suggestions based on your data model.
When you work with properties of a person, then you'll see suggestions for name and date_of_birth.
```
. Select the *Run Cell* icon to render the Markdown text.
. Create another cell to continue building your notebook.
