= Create a table in your keyspace
:slug: creating-a-table-in-your-keyspace

Create tables in your database using Astra's REST API. Use the authorization token you generated to create a table in your keyspace.
A keyspace is like a bucket that holds your tables.
You can create different keyspaces for groups of tables.

== Prerequisites
. [Generate an authorization token](doc:generating-authorization-token).
. After generating an authorization token, run the following request to get all available keyspaces:
```
curl --request GET \\
 --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/schemas/keyspaces \\
 --header 'accept: application/json' \\
 --header 'x-cassandra-request-id: {unique-UUID}' \\
 --header "x-cassandra-token: ${ASTRA_AUTHORIZATION_TOKEN}"
```

 * Optional `{unique-UUID}` is a randomly-generated UUID that is unique for the authorization request

The list of all available keyspaces returns:
```
{
 "data": [
 {"name": "system_schema"},
 {"name": "system"},
 {"name": "system_backups"},
 {"name": "system_distributed",
   "datacenters": [
   {"name": "dc-1", "replicas": 1}]
 },
 {"name": "system_traces",
   "datacenters": [
   {"name": "dc-1", "replicas": 1}]
 },
 {"name": "system_auth",
   "datacenters": [
   {"name": "dc-1", "replicas": 1}]
 },
 {"name": "datastax_sla",
   "datacenters": [
   {"name": "dc-1", "replicas": 1}]
 },
 {"name": "data_endpoint_auth",
   "datacenters": [
   {"name": "dc-1", "replicas": 1}]
 },
 {"name": "my_keyspace",
   "datacenters": [
   {"name": "dc-1", "replicas": 1}]
 }]
}
```

Find the name of the keyspace for your <+++<glossary:database>+++>.
In this example, `my_keyspace` is the keyspace name we'll use to create a table in.

== Procedure
. Copy the following request, which you use to create a `products` table in the specified keyspace.

In the following example, `products` is the table name.
The table columns are `name`, `description`, `price`, and `created`.

A special column, `partitionKey`, defines the outermost grouping of data, similar to a schema in a relational database.
In this example, we'll use the `name` column to group our data.
```
curl --request POST \\
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/schemas/keyspaces/${ASTRA_DB_KEYSPACE}/tables \\
  --header 'accept: */*' \\
  --header 'content-type: application/json' \\
  --header 'x-cassandra-request-id: {unique-UUID}' \\
  --header "x-cassandra-token: ${ASTRA_AUTHORIZATION_TOKEN}" \\
  --data '{"name":"products","ifNotExists":true,"columnDefinitions": [
    {"name":"id","typeDefinition":"uuid","static":false},
    {"name":"name","typeDefinition":"text","static":false},
    {"name":"description","typeDefinition":"text","static":false},
    {"name":"price","typeDefinition":"decimal","static":false},
    {"name":"created","typeDefinition":"timestamp","static":false}],
    "primaryKey":{"partitionKey":["id"]},
    "tableOptions":{"defaultTimeToLive\":0}}'
```

. Replace the following values with the values for your database:+++</glossary:column>+++
 * Modify `my_keyspace` to match the name of your keyspace.
 * Optional: Enter a `+{unique-UUID}+` for the request.
 * In the `--data` option of the call, specify the name of the table, and then define the table columns using the `columnDefinitions` parameter.

. Run the cURL call to create a `products` table in the specified keyspace.
If the call is successful, a message returns indicating:
```
{"name":"products"}
```
