= Delete columns in your table
:slug: deleting-columns-in-your-table

Alter the schema of your database tables by removing columns using Astra's REST API.

You can delete columns from a table.
Use the link:ref:deletecolumn-1[Delete a column] endpoint to remove the columns in the table you created previously.

Prerequisites
. link:doc:generating-authorization-token[Generate an authorization token].
. link:doc:creating-a-table-in-your-keyspace[Create a table in your keyspace].

== Procedure
. Copy the following request, which you use to delete columns in the specified table.
```
curl --request DELETE \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v1/keyspaces/{my_keyspace}/tables/{table_name}/columns/{columnName} \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --header 'x-cassandra-request-id: {unique-UUID}' \
  --header "x-cassandra-token: ${ASTRA_AUTHORIZATION_TOKEN}"
```

. Modify `my_keyspace` to match the name of your keyspace.
. Replace `table_name` with the name of the table from which you want to delete a column.
In this example, enter `products` as the table name.
. Replace `columnName` with the name of the column you want to delete.
In this example, enter `description` as the table name.
. Enter a `unique-UUID` for the request.
```
curl --request DELETE \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v1/keyspaces/betterbotz/tables/products/columns/price \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --header 'x-cassandra-request-id: xyzaa27b-de8e-4afc-8431-8f06a326047d' \
  --header "x-cassandra-token: $\{ASTRA_AUTHORIZATION_TOKEN}"
```

. Run the cURL call.
If the call is successful, a `204` message is returned.
