= Delete rows in your table
:slug: deleting-rows-in-your-table

Delete data in your tables using Astra's REST API.

You can delete rows in a table.
Use the [Delete rows](ref:deleterow-1) endpoint to remove the rows in the table you created previously.

== Prerequisites
. [Generate an authorization token](doc:generating-authorization-token).
. [Create a table in your keyspace](doc:creating-a-table-in-your-keyspace).
. [Add rows to your table](doc:adding-rows-to-your-table).

== Procedure
. Copy the following request, which you use to delete rows in the specified table.
=== REST
```
curl --request DELETE \\
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/keyspaces/${ASTRA_DB_KEYSPACE}/table_name}/{partitionkey} \\
  --header 'accept: application/json' \\
  --header 'content-type: application/json' \\
  --header 'x-cassandra-request-id: \{unique-UUID}' \\
  --header "x-cassandra-token: ${ASTRA_AUTHORIZATION_TOKEN}"
```

. Modify `my_keyspace` to match the name of your keyspace.
. Replace `table_name` with the name of the table from which you want to delete a <+++<glossary:row>+++>.
In this example, enter `products` as the table name.
. Replace `partition-key` with the name of the partition key you want to delete.
In this example, enter `e9b6c02d-0604-4bab-a3ea-6a7984654631` as the partition key.
. Enter a `{unique-UUID}` for the request.
```
curl --request DELETE \\
 --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/keyspaces/${ASTRA_DB_KEYSPACE}/products/e9b6c02d-0604-4bab-a3ea-6a7984654631 \\
 --header 'accept: application/json' \\
 --header 'content-type: application/json' \\
 --header 'x-cassandra-request-id: xyzaa27b-de8e-4afc-8431-8f06a326047d' \\
 --header "x-cassandra-token: ${ASTRA_AUTHORIZATION_TOKEN}"
```
. Run the cURL call.
If the call is successful, no message is returned, but the row is deleted.
