= Migrate DataStax drivers
:slug: migrating-datastax-drivers-to-connect-to-astra-databases

If using an existing version of a DataStax driver, migrate a version that is compatible with DataStax Astra.

To migrate your DataStax Apache Cassandra or DataStax Enterprise (DSE) driver, follow the instructions to change any required dependencies and modify the connection code to use the new DataStax Astra API.

After migrating, follow the instructions to xref:connecting-to-astra-databases-using-datastax-drivers.adoc[connect to your Astra database using the DataStax drivers].

* xref:migrating-your-datastax-c-driver-to-connect-with-astra-databases.adoc[Migrate C{pp} driver]
* xref:migrating-the-c-driver-to-connect-with-astra-databases.adoc[Migrate C# driver]
* xref:migrating-your-datastax-java-driver-to-connect-with-astra-databases.adoc[Migrate Java driver]
* xref:migrating-your-datastax-nodejs-driver-to-connect-with-astra-databases.adoc[Migrate Node.js driver]
* xref:migrating-your-datastax-python-driver-to-connect-with-astra-databases.adoc[Migrate Python driver]
