= Migrate C++ driver
:slug: migrating-your-datastax-c-driver-to-connect-with-astra-databases

Complete the following procedure to migrate your existing DataStax C++ driver to a version that is capable of connecting to Astra databases created using DataStax Astra.

== Prerequisites
. xref:creating-your-astra-database.adoc[Create a database] using https://astra.datastax.com[DataStax Astra].
. xref:obtaining-database-credentials.adoc[Download the secure connect bundle] to obtain connection credentials for your DataStax Astra database.
[TIP]
====
Alternatively, xref:providing-access-to-astra-databases[have a teammate provide access to their Astra database].
====

. Download the DataStax C++ driver and dependency packages for your platform using the links in the following table:
===DataStax C++ driver download links
[cols=2*,options=header]
|===
|Platform
|Download links

|CentOS 6
|

|CentOS 7
|

|Ubuntu 14.04
|

|Ubuntu 16.04
|

|Ubuntu 18.04
|

|Windows
|

|===

Other platforms should build the driver from the https://github.com/datastax/cpp-driver[source code packages].

. Using the packages you downloaded, follow the https://docs.datastax.com/en/developer/cpp-dse-driver/latest/installation/[installation instructions] for your platform to install the DataStax C++ driver.

== Procedure
. In your existing DataStax C++ driver code, modify the connection code to use the DataStax Astra API.
[NOTE]
====
Both the DataStax C++ driver for Apache Cassandra and the DataStax Enterprise (DSE) C++ driver use the same code to connect and query your Astra database.
When using the DSE C++ driver, use the header `#include <dse.h>`.
====

The `secure_connect_bundle` must include the absolute path to your Astra database credentials (`+secure-connect-**database_name**.zip+`).
=== C++
```
cass_cluster_set_credentials(cluster, "username", "password");

  CassFuture* connect_future = cass_session_connect(session, cluster);
  if (cass_future_error_code(connect_future) == CASS_OK) {
    * Use the session to run queries _
    }
  else {
    _ Handle error *
  }
```
. Build and link your application against the DataStax C++ driver.
* *Linux or macOS*
[NOTE]
====
For static linking, use `cassandra_static.a` or `dse_static.a`.
====

=== DataStax C++ driver for Apache Cassandra
```
cc connect-database.c -I/path/to/cassandra.h -L/path/to/cassandra.so -lcassandra
```

=== DSE C++ driver
```
``pass:c[cc connect-database.c -I/path/to/dse.h -L/path/to/dse.so -ldse
```

* **Windows**
Include these libraries in your Microsoft Visual Studio project by adding them to the project’s properties under ]``Configuration Properties/Linker/Input/Additional Dependencies``.
[NOTE]
====
For static linking, use ``cassandra_static.lib`` or ``dse_static.lib``pass:c[.
====

_DataStax C++ driver for Apache Cassandra_
Link your application against ``cassandra.lib``.
Your application will also require ``cassandra.dll` to be in your runtime path.

_DSE C++ driver_
Link your application against `dse.lib`.
Your application will also require `dse.dll` to be in your runtime path.
