= Read documents
:slug: read-documents

==Retrieve all documents
Let's check that the document was inserted.
Send a GET request to `+/v2/namespaces/{namespace_name}/collections/{collections_name}+` to retrieve all the documents:
```
curl --request GET \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/namespaces/betterbotz/collections/products?page-size=3 \
  --header "X-Cassandra-Token: $ASTRA_AUTHORIZATION_TOKEN" \
  --header 'Content-Type: application/json'
```

===Sample results
```
{
  "data":
    {"3c62d695-1ea4-45ae-8cfb-e82e1ed1d238":
      {"description": "Heavy lift arms capable of lifting 1,250lbs of weight per arm. Sold as a set.",
       "name": "Heavy Lift Arms"},
       "e9b6c04d-0604-4bab-a3ea-6a7984644631":
         {"description": "Medium lift arms capable of lifting 850lbs of weight per arm. Sold as a set.",
         "dimensions":
           {"height": 43,
            "length": 13,
            "width": 27},
            "name": "Medium Lift Arms"}
        }
}
```

==Retrieving a specified document
Let's check that the data was inserted for a particular document.
Send a GET request to `+/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}+` to retrieve the document:
```
curl --request GET \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/namespaces/betterbotz/collections/products/e9b6c04d-0604-4bab-a3ea-6a7984644631 \
  --header "X-Cassandra-Token: $ASTRA_AUTHORIZATION_TOKEN" \
  --header 'Content-Type: application/json'
```

===Sample results
```
{
  "documentId": "e9b6c04d-0604-4bab-a3ea-6a7984644631",
  "data":
    {
      "description": "Medium lift arms capable of lifting 850lbs of weight per arm. Sold as a set.",
      "dimensions":
        {
          "height": 43,
          "length": 13,
          "width": 27
        },
      "name": "Medium Lift Arms"
    }
}
```

It is possible to get a value for a particular field in a document using one of two methods, either a where clause or a document-path.
These methods can retrieve information from a document or a sub-document.

==Retrieving a document using a where clause
Now let's search for a particular document using a where clause.
Send a GET request to `+/v2/namespaces/{namespace_name}/collections/{collections_name}?{where-clause}+` to get the same information:
[NOTE]
====
To run `WHERE` clauses using the Document API in Astra, you must URL encode your clause.
For example `{"name":{"$eq":"Heavy Lift Arms"}}` would be written as `%7B%22name%22%3A%7B%22%24eq%22%3A%22Heavy%20Lift%20Arms%22%7D%7`."
====

```
curl --request GET \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/namespaces/betterbotz/collections/products?where=%7B%22name%22%3A%7B%22%24eq%22%3A%22Heavy%20Lift%20Arms%22%7D%7D \
  --header "X-Cassandra-Token: $ASTRA_AUTHORIZATION_TOKEN" \
  --header 'Content-Type: application/json'
```

===Sample results
```
{
  "data":
    {
      "3c62d695-1ea4-45ae-8cfb-e82e1ed1d238":
        {
          "description": "Heavy lift arms capable of lifting 1,250lbs of weight per arm. Sold as a set.",
          "name": "Heavy Lift Arms"
        }
    }
}
```

Note that the where clause must be url encoded, so curly brackets are escaped with \ and spaces must be replaced with %20.
Also, the full document is returned, as opposed to the value of the field specified in the {document-path} like the next command.

You can also retrieve documents using a WHERE clause that searches sub-documents:
```
curl --request GET \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/namespaces/betterbotz/collections/products?where=%7B%22dimensions.length%22%3A%7B%22%24eq%22%3A13%7D%7D \
  --header "X-Cassandra-Token: $ASTRA_AUTHORIZATION_TOKEN" \
  --header 'Content-Type: application/json'
```

====Sample results
```
{
  "data":
    {
      "e9b6c04d-0604-4bab-a3ea-6a7984644631":
        {
          "description": "Medium lift arms capable of lifting 850lbs of weight per arm. Sold as a set.",
          "dimensions":
            {
              "height": 43,
              "length": 13,
              "width": 27
            }
          "name": "Medium Lift Arms",
          "price": "2199.99"
        }
    }
}
```

==Retrieving a specific portion of a document with document path
To find a particular value, send a GET request to `+/v2/namespaces/{namespace_name}/collections/{collections_name}/{document-id}/{document-path}+` to retrieve the type of weights Joey has done in his workout:
```
curl --request GET \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/namespaces/betterbotz/collections/products/e9b6c04d-0604-4bab-a3ea-6a7984644631/dimensions/length \
  --header "X-Cassandra-Token: $ASTRA_AUTHORIZATION_TOKEN" \
  --header 'Content-Type: application/json'
```

===Sample results
```
{
  "documentId": "e9b6c04d-0604-4bab-a3ea-6a7984644631",
  "data": 13
}
```

In this case, the sub-document weights is the document-path specified to retrieve that data about the reps, type, and weight.
```
curl --request GET https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/namespaces/betterbotz/collections/products/e9b6c04d-0604-4bab-a3ea-6a7984644631/dimensions \
  --header "X-Cassandra-Token: $ASTRA_AUTHORIZATION_TOKEN" \
  --header 'Content-Type: application/json'
```

===Sample results
```
{
  "documentId": "e9b6c04d-0604-4bab-a3ea-6a7984644631",
  "data":
    {
    "height": 43,
    "length": 13,
    "width": 27
    }
}
```
