= Update rows in your table
:slug: updating-rows-in-your-table

Update data in your tables using Astra's REST API.

[DANGER]
====
Needs more testing and to be fixed.
====

After creating a table in your keyspace and adding rows, you can update data.
Use the [Update rows](ref:updaterow-1) endpoint to update rows in the table you created previously.

== Prerequisites
. [Generate an authorization token](doc:generating-authorization-token).
. [Create a table in your keyspace](doc:creating-a-table-in-your-keyspace).
. [Add rows to your table](doc:adding-rows-to-your-table).

== Procedure
. Copy the following request, which you use to update rows in the specified table.
```
curl --request POST \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/keyspaces/${ASTRA_DB_KEYSPACE}/tables/{table_name}/rows \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --header 'x-cassandra-request-id: {unique-UUID}' \
  --header "x-cassandra-token: ${ASTRA_AUTHORIZATION_TOKEN}" \
  --data '{"columns":[{"name":"name0","value":"value0"},{"name":"name1","value":"value1"},{"name":"name2","value":"value2"},{"name":"name3","value":"value3"},{"name":"name4","value":"value4"},{"name":"name5","value":"value"}]}'
```

. Modify `my_keyspace` to match the name of your keyspace.
. Replace `table_name` with the name of the table you want to update.
In this example, enter `products` as the table name.
. Enter a `\{unique-UUID}` for the request.
. In the `--data` option of the call, use the `columns` parameter to define each row.

In each row, `name` indicates the column name and `value` indicates the corresponding value.
For example, the following example updates the row for the **Heavy Lift Arms** product, updating the price.
```
curl --request PATCH \
  --url https://${ASTRA_CLUSTER_ID}-${ASTRA_CLUSTER_REGION}.apps.astra.datastax.com/api/rest/v2/keyspaces/${ASTRA_DB_KEYSPACE}/products/e9b6c02d-0604-4bab-a3ea-6a7984654631 \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --header 'x-cassandra-request-id: xyzaa27b-de8e-4afc-8431-8f06a326047d' \
  --header "x-cassandra-token: ${ASTRA_AUTHORIZATION_TOKEN}" \
  --data '{"columns":[{"name":"id","value":"e9b6c02d-0604-4bab-a3ea-6a7984654631"},{"name":"name","value":"Heavy Lift Arms"},{"name":"description","value":"Heavy lift arms capable of lifting 1,250 lbs of weight per arm. Sold as a set."},{"name":"price","value":"9999.99"},{"name":"created","value":"2012-04-23T18:25:43.511Z"}]}'
```

. Run the cURL call with the `--data` option to add the rows you defined to the `products` table in the specified keyspace.
If the call is successful, a message returns indicating that the operation was successful, and the number of rows that were modified:
```
{"success": true,"rowsModified": 1}
```
