= Change your login password
:slug: changing-your-login-password

Complete the following steps if you know your login password for the DataStax Astra console and want to change it.

==Procedure
. Open a browser, navigate to link:astra.datastax.com[DataStax Astra], and log in.
. In the upper-right corner, select the arrow next to your username and select *Reset Password*.
A password reset link is sent to the email address associated with your account.
If the email address you entered is found in the <+++<glossary:database>+++>, a message is sent to that address with a link to reset your password.
The link expires within 12 hours.
. In the password reset email, select **Link to account update** to reset your password.
. Select **Click here to proceed**.
. In the **Update Password** window, enter a new password, confirm the password, and select **Submit** to change your password.

==Results
Your new password is recorded and can be used for subsequent logins to the DataStax Astra console.
Use your new password to log in.+++</glossary:database>+++
