= IAM DRAFT: Create custom user roles
:slug: create-custom-user-roles

If the default roles don't meet your requirements, create custom roles to use when you invite users.

==Procedure
. From your *Organization* page, select *Role Management*.
. Select *Add Custom Role*.
. Enter the name you want to use for your custom role.
This name should help you easily identify when you want to assign this role to users.
. Select the Organization, Keyspace, and Table permissions you want to assign to your custom role.
[IMPORTANT]
====
**Database- and keyspace-specific permissions**
By default, your selected permissions are applied to all databases and keyspaces within your organization.
====
. If you need to apply your selected permissions to specific databases or keyspaces, switch off the toggle that applies the permissions to all databases in the organization.
Select the specific databases or keyspaces to which you want the apply the permissions.

Invited users are listed as pending until they accept the invitation to join your organization.

To see your custom roles, select _Role Management_ within your Organization.
