= Astra database limits
:slug: datastax-astra-database-limits

DataStax Astra sets limits for databases to ensure good practices, foster availability, and promote optimal configurations for your database.

DataStax Astra offers a Free tier, allowing you to create an Astra database with 5 GB for free.
Create a database with just a few clicks and start developing within minutes.

You can create up to 5 databases per region, and add a total of 20 capacity units (CUs) per database (10TBs).
To adjust the capacity unit limits, contact [DataStax Support](https://houston.datastax.com/hc/requests/new).

[NOTE]
====
Astra provides one database on the Free tier per user.
====

The following limits are set for all databases not on the Free tier created using DataStax Astra.
These limits ensure good practices, foster availability, and promote optimal configurations for your database.

== Columns

[cols=3*,options=header]
|===
|Parameter
|Limit
|Notes

|Size of values in a single column
|5 MB
|Hard limit.

|Number of columns per table
|50
|Hard limit.

|===

== Tables

[cols=3*,options=header]
|===
|Parameter
|Limit
|Notes

|Number of tables per database
|200
|A warning is issued when the database exceeds 100 tables.

|Table properties
|Fixed
|	All table properties are fixed except for https://docs.datastax.com/en/astra-cql/doc/cql/cql/cql_using/useExpire.html[Expiring data with time-to-live].

|Secondary index
|1
|Limit is per table.

|Materialized view
|2
|Limit is per table. A warning is issued if the materialized view will create large partitions.

|===

== Cassandra Query Language (CQL)

[NOTE]
====
At this time, user-defined functions (UDFs) and user-defined aggregate functions (UDAs) are not enabled.
====

[cols=3*,options=header]
|===
|Parameter
|Limit
|Notes

|Consistency level
|Fixed
|Supported consistency levels:
 Reads: Any https://docs.datastax.com/en/dse/6.8/dse-arch/datastax_enterprise/dbInternals/dbIntConfigConsistency.html[supported consistency level] is permitted
 Writes: LOCAL_QUORUM and LOCAL_SERIAL

|Compaction strategy
|Fixed
|Only the https://docs.datastax.com/en/astra-cql/doc/cql/cql/cql_reference/cql_commands/cqlCreateTable.html#compactSubprop__STCS[SizeTieredCompaction strategy] is supported.

|Lists
|Fixed
|Cannot `UPDATE`, `INSERT`, or `DELETE` a list value by index because Astra does not allow list operations which perform a read-before-write.

|Page size
|Fixed
|The proper page size is configured automatically.

|Large partition
|Warning
|A warning is issued if reading or compacting a partition that exceeds 50 MB.

|===

== cassandra.yaml
If you are an experienced Cassandra or DataStax Enterprise, you are likely familiar with editing the `cassandra.yaml` file.
For Astra, the `cassandra.yaml` file cannot be configured.

The following limits are included in Astra:

````
// for read requests
        page_size_failure_threshold_in_kb =  512
        in_select_cartesian_product_failure_threshold =  25
        partition_keys_in_select_failure_threshold = 20
        tombstone_warn_threshold = 1000
        tombstone_failure_threshold = 100000

// for write requests
        batch_size_warn_threshold_in_kb = 5
        batch_size_fail_threshold_in_kb = 50
        unlogged_batch_across_partitions_warn_threshold = 10
        user_timestamps_enabled = true
        column_value_size_failure_threshold_in_kb = 5 * 1024L
        read_before_write_list_operations_enabled = false

// for schema
        fields_per_udt_failure_threshold = 10
        collection_size_warn_threshold_in_kb =  5 * 1024L
        items_per_collection_warn_threshold =  20
        columns_per_table_failure_threshold = 50
        secondary_index_per_table_failure_threshold = 1
        materialized_view_per_table_failure_threshold = 2
        tables_warn_threshold = 100
        tables_failure_threshold = 200

// for node status
        disk_usage_percentage_warn_threshold =  70
        disk_usage_percentage_failure_threshold =  80
        partition_size_warn_threshold_in_mb =  100

// SAI Table Failure threshold
        sai_indexes_per_table_failure_threshold = 10
````
