= Install Service Catalog
:slug: install-service-catalog

The https://www.openservicebrokerapi.org/[Open Service Broker API] provides a standard RESTful interface for provisioning services from a provided catalog, such as Astra databases. Each service is provisioned as part of a binding which may contain sizing information such as a capacity value or size of the instance.

[IMPORTANT]
====
The Astra Service Broker supports only Kubernetes v1.13 and later.
====

==Prerequisites
* Running Kubernetes cluster you can access via command line
* https://helm.sh/docs/intro/install/[Helm package manager] for Kubernetes
* https://svc-cat.io/docs/install/#installing-the-service-catalog-cli[Service Catalog command-line interface]
* https://astra.datastax.com[DataStax Astra] account with xref:manage-service-account.adoc[service account credentials]

==Procedure
. For each Kubernetes cluster, install the service catalog:
````
helm repo add service-catalog https://kubernetes-sigs.github.io/service-catalog \
helm repo update \
helm install catalog service-catalog/catalog --namespace catalog --create-namespace
````

. Create a Kubernetes secret with the xref:manage-service-account.adoc[service account information] from Astra:
````
kubectl create secret generic astra-creds \
  --from-literal=username=unused \
  --from-literal=password=`echo '<service_account_creds>'| base64`
````

Replace the `<service_account_credentials>` with the snippet of JSON from your Astra service account.
For example:

````
{
  "clientId":"<clientId>",
  "clientName":"<clientName>",
  "clientSecret":"<clientSecret>"
}
````

. Register the broker via the ServiceBroker custom resource:
````
svcat register astra \
  --url https://broker.astra.datastax.com/ \
  --basic-secret astra-creds
````

The Service Catalog automatically queries for available services on Astra and displays the available xref:service-tier-options.adoc[plan options]:
````
svcat marketplace
````

````
NAME    NAMESPACE       CLASS                   DESCRIPTION
+-----------+-----------+----------------+------------------------------------+
A10       default     astra-database   6 vCPU, 24GB DRAM, 20GB
                                    Storage
A20       default     astra-database   12 vCPU, 48GB DRAM, 40GB
                                    Storage
developer   default   astra-database   Free tier: Try Astra with
                                    no obligation. Get 5 GB of
                                    storage, free forever.

...
````

[NOTE]
====
This result shows only a portion of the available Astra tiers from the Service Catalog.
====
