= Using kubetcl to provision and bind an Astra Database
:slug: kubectl-provisioning-of-service-broker

The [Open Service Broker API](https://www.openservicebrokerapi.org/) provides a standard RESTful interface for provisioning services from a provided catalog, such as Astra databases.

[IMPORTANT]
====
The Astra Service Broker supports only Kubernetes v1.13 and later.
====

== Prerequisites
* Running Kubernetes cluster you can access via command line
* https://helm.sh/docs/intro/install/[Helm package manager] for Kubernetes
* https://svc-cat.io/docs/install/#installing-the-service-catalog-cli[Service Catalog command-line interface]
* https://astra.datastax.com[DataStax Astra] account with xref:manage-service-account.adoc[service account credentials]
* xref:install-service-catalog.adoc[Install Service Catalog]

== Provision your database using `kubectl`"
. Create a file called `astra.yaml` to describe the type of instance you need:
````
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: <db_name>
  namespace: default
spec:
  parameters:
    capacity_units: 1
    cloud_provider: <cloud_provider>
    keyspace: <keyspace_name>
    region: <region>
  serviceClassExternalName: astra-database
  servicePlanExternalName: <plan_option>
````

. Apply the `astra.yaml` file to provision your database:
````
kubectl apply -f astra.yaml
````
[IMPORTANT]
====
The time required to provision a database depends on the selected plan.
For Free databases, it can take several minutes; for larger paid databases, it can take tens of minutes.
====

== Check your instance status
The service catalog handles the provisioning and communication with Astra.
After a few minutes, check the instance status:

````
kubectl get serviceinstances <db_name>
````

You will see the following results:
````
NAME    CLASS                                               PLAN                                STATUS   AGE
<db_name>   ServiceClass/26b3fbe6-0c18-5140-8ac6-87d03b5b4148   1c9bb5ac-6609-5af5-a747-ecf1d093cc7f   Ready    3m20s
````

== Bind your instance
The process of retrieving service credentials is known as binding. Create a new YAML file to describe your ServiceBinding resource. In this example, we create `astra-service-binding.yaml`:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: <database_name>
spec:
  externalID: 9a412237-1c66-4d43-b5e6-cd92d7b61779
  instanceRef:
    name: <database_name>
  secretName: <database_name>
```

Apply the `astra-service-binding.yaml` file to bind your service credentials:
````
kubectl apply -f astra-service-binding.yaml
````

After receiving this request Service Catalog handles retrieving the credentials from Astra and placing them within a local kubernetes secret at the same name as our binding:
````
kubectl get secrets +++<database_name>+++-o yaml
````

You will see the following results:
````
data:
  cql_port: 9042
  external_endpoint: ...astra.datastax.com
  encoded_external_bundle: BASE64_ENCODED_CONNECT_BUNDLE_ZIP
  internal_endpoint: ...internal.astra.datastax.com
  encoded_internal_bundle: BASE64_ENCODED_CONNECT_BUNDLE_ZIP
  keyspace: <keyspace_name>
  local_datacenter: dc-1
  password: REDACTED
  port: 1337
  tls_ca_cert: PEM_ENCODED_CA_CERT
  tls_cert: PEM_ENCODED_APPLICATION_CERT
  tls_key: PEM_ENCODED_APPLICATION_KEY
  username: REDACTED
kind: Secret
metadata:
  name: <database_name>
type: Opaque
````

[NOTE]
====
If you unbind your instance, the credentials are rotated and will no longer work. You must bind the instance again before you can connect.
====

==Try it out
The xref:obtaining-database-credentials.adoc[secure connect bundle] is stored inside of the `encoded_external_bundle` and `encoded_internal_bundle` keys. This is the information with the username and password you need to configure the driver. You can see this example in the https://github.com/spring-petclinic/spring-petclinic-reactive/tree/master/k8s[Spring Reactive Pet Clinic sample app].
