= Manage service account for your organization
:slug: manage-service-account

==Create your service account
. Open a browser, navigate to https://astra.datastax.com[DataStax Astra], and log in.
. On the *Organization* page, select *Add Service Account*.

The *Service Account* information will be populated to show your *Client ID* and *Client Name*.

==Copying your service account secret
. Select the overflow menu for your <+++<glossary:service account="">+++>.
. Select **Copy Credentials**.
````
{\n\"clientId\":\"58391caa-5c48-4e28-8b70-da3fe1624f3c\",\n\"clientName\":\"user@domain.com\",\n\"clientSecret\":\"42d9e2h3-4d25-40k8-aa1a-c9f6cc73ef10\"\n}
````
Use your service account secret to [Authenticate your service account](doc:authenticating-your-service-account) via the [DevOps API](ref:authentication-1).

==Refreshing your service account secret
If there are concerns that your service account has been compromised, you can refresh your client secret and update your API requests.+++</glossary:service>+++
. Select the overflow menu for your service account.
. Select *Refresh Client Secret*.
. Confirm that you want to refresh your client secret, which will prevent any users from accessing the <+++<glossary:database>+++> API with the previous client secret.
. Select **Yes**.+++</glossary:database>+++
