= Manage multiple keyspaces
:slug: managing-keyspaces

Creating a database with multiple keyspaces allows you to create different data models for each keyspace or store unique data in unique keyspaces.
Multiple keyspaces within a single <+++<glossary:region>+++> allows for an application built on a per-keyspace data model.

Multiple keyspaces allow for greater data availability in multiple regions. With multiple keyspaces in multiple regions, you can control what application data is available by each region. For example, if you want an app's data to live in regions 1 and 3, but not in region 2, you can do this by managing the keyspace for that schema.
==Adding a new keyspace
. Open a browser, navigate to [DataStax Astra](astra.datastax.com), and log in.
. On the **Dashboard** page, select the <+++<glossary:database>+++> name to access the **Summary** page for your selected database.
. Select **Add Keyspace**.
. Enter the name of the new <+++<glossary:keyspace>+++>.
. Select **Save**.+++</glossary:keyspace>++++++</glossary:database>++++++</glossary:region>+++

Your list of keyspaces displays on the *Summary* page for your database.

==Removing a keyspace

[CAUTION]
====
If you delete a keyspace, all data in that keyspace is removed and cannot be recovered.
====

. Open a browser, navigate to link:astra.datastax.com[DataStax Astra], and log in.
. On the *Dashboard* page, select the database name to access the *Summar* page for your selected database.
. Select the overflow menu for the keyspace you want to delete.
. Select *Delete*.
. In the *Delete keyspace* menu, type in the name of the keyspace to delete.
. Select *Delete Keyspace*.

Your list of keyspaces will be updated on the *Summary* page to show only the remaining keyspaces for your database.
