= Obtain database credentials
:slug: obtaining-database-credentials

To connect to your Astra database, download the secure database bundle from the DataStax Cloud console that contains the connection credentials.

== Prerequisite
xref:creating-your-astra-database.adoc[Create your Astra database] using the DataStax Astra console.

== Getting your secure connect bundle
. Open a browser, navigate to https://astra.datastax.com/[DataStax Astra], and log in.
. From your *Dashboard* page, select your database.
. On the **Summary** page, select **Connect**.
. Select **Driver** as your **Connection Method**.
. Select **Download Secure Connect Bundle**.

If you've enabled VPC peering, you can also **Download External Secure Connect Bundle** for use within your VPC peering.
The **secure-connect-*database_name*.zip** file downloads, which contains the security certificates and credentials for your database.
[TIP]
====
Alternatively, you can right-click the **Download credentials** link, copy the link source, and then use a `curl` command to download the **secure-connect-*database_name*.zip** file:
````
curl -L "<secure-connect-database_name-download-URL>" > database_name.zip
````
====

== Sharing your secure connect bundle
Although teammates can access your Astra database, it will not display in their list of available databases under *My Databases* in the DataStax Astra console.

After you create an Astra database, you can grant access to other members of your team by providing them with the database credentials and connection details for your database.
[WARNING]
====
Be careful when sharing connection details.
Providing this information to another user grants them access to your Astra database and ownership capabilities, such as making modifications to the database.

For security, delete downloaded connection credentials after sending them to your teammate.
====
