= Using svcat to provision and bind an Astra Database
:slug: svcat-provisioning-of-service-broker

The [Open Service Broker API](https://www.openservicebrokerapi.org/) provides a standard RESTful interface for provisioning services from a provided catalog, such as Astra databases.

[IMPORTANT]
====
The Astra Service Broker supports only Kubernetes v1.13 and later.
====

== Prerequisites
* Running Kubernetes cluster you can access via command line
* https://helm.sh/docs/intro/install/[Helm package manager] for Kubernetes
* https://svc-cat.io/docs/install/#installing-the-service-catalog-cli[Service Catalog command-line interface]
* https://astra.datastax.com[DataStax Astra] account with xref:manage-service-account.adoc[service account credentials]
* xref:install-service-catalog.adoc[Install Service Catalog]

== Provision your database using `svcat`
```
svcat provision <db_name>
--class astra-database
--plan <plan_option>
--params-json
'{
  "cloud_provider": "<cloud_provider>",
  "region": "<region>",
  "capacity_units": 1,
  "keyspace": "<keyspace_name>"
}'
```

You will see the following results:
```
Name:       <db_name>
  Namespace:   default
  Status:
  Class:
  Plan:

Parameters:
  capacity_units: 1
  cloud_provider: <cloud_provider>
  keyspace: <keyspace_name>
  region: <region>
```

== Check your instance status
The service catalog handles the provisioning and communication with Astra.
After a few minutes, check the instance status:+++</region>++++++</keyspace_name>++++++</cloud_provider>+++

````
svcat get instances
````

You will see the following results:
````
NAME  NAMESPACE   CLASS   PLAN   STATUS
+-------+-----------+-------+------+--------+
<db_name>   default                   Ready
````

==Bind your instance
The process of retrieving service credentials is known as binding. Bind your database instance:
````
svcat bind <database_name>
````

You will see the following results:
````
Name:     <database_name>
Namespace:   default
Status:
Secret:   <database_name>
Instance: <database_name>

Parameters:
No parameters defined
````

[NOTE]
====
If you unbind your instance, the credentials are rotated and will no longer work. You must bind the instance again before you can connect
====

==Try it out
The xref:obtaining-database-credentials.adoc[secure connect bundle] is stored inside of the `encoded_external_bundle` and `encoded_internal_bundle` keys. This is the information with the username and password you need to configure the driver. You can see this example in the https://github.com/spring-petclinic/spring-petclinic-reactive/tree/master/k8s[Spring Reactive Pet Clinic sample app].
