= GCP VPC peering
:slug: using-gcp-vpc-peering

By creating a virtual private cloud (VPC), you can connect your GCP resources and Astra databases. VPC peering allows you to communicate across the VPCs.

[INFORMATION]
====
VPC peering is available on only Production Workload databases.
For more about VPC peering on Astra databases hosted on GCP, see https://cloud.google.com/vpc/docs/vpc-peering[VPC Network Peering overview].
====

== Prerequisites
* Create a VPC in your GCP account.
* Create your Astra <+++<glossary:database>+++>.
See [Creating your Astra database](doc:creating-your-astra-database).

== Procedure
The procedure is a two-step process using the DataStax Astra Console and the Google Cloud Console.+++</glossary:database>+++

=== Astra Console
. From your database *Summary*, select *Add Peering Connection*.
. In *Add Peering Connection*, enter the GCP project name in the *Project ID*.
. Enter the *VPC Network Name* from the list of VPCs in the VPC dashboard of your GCP account.
For example, _default_.
. Select *Initiate*.

=== Google Cloud Console
. Open your GCP project.
. In the left sidebar, navigate to *VPC Network*.
. Open *VPC network peering*.
. Select *Create Connection* and then *Continue*.
. On the *Create peering connection* dialog, enter:
 * A name for the connection you're creating
 * Your VPN network  You may select _default_ from the list.
 * Under *Peered VPC Network*, enable *In another project* and enter:
    * **Astra Project ID:** Found on your database page in **Network Peering**. For example, `esmrahul3x7as3xbcj2grtexarskq`.
    * **VPC network name:** Found on your database page in **Network Peering**. For example, `dse-4240ebe6-72e1-4ea1-ac25-cc728d9fa9ff`.
. Select *Initiate Peering*.
