= View your databases
:slug: viewing-database-summary

View all databases in your organization, and select a database to view detailed information about the database.

The *Dashboard* shows all of your databases within your organization, including databases you created and databases created by other team members.
From here, you can select an individual database name to manage and connect those databases.

Selecting a database in DataStax Astra provides access to detailed information about the database.
You can view the keyspaces, size and location of the database, and the estimate cost per hour.

==Procedure
. Open a browser, navigate to [DataStax Astra](astra.datastax.com), and log in.
. On the **Dashboard** page, select the database name to access the **Summary** page for your selected database.
[NOTE]
====
You can only view connection details and xref:managing-databases.adoc[database management operations] for databases that you created.
====

. On the **Summary** tab, you can see several database details:

* Database Name
* Status
* Cost Per Hour
* Compute Size
* Replication Factor
* Current Capacity
* Current Usage
* Cluster ID
* Database Username
* Regions
* Keyspaces
