= View health and metrics
:slug: viewing-database-health-and-metrics


Select a database to view health metrics and performance information.
When selecting a database, you can view health metrics that include information regarding latency and throughput to the database.
These metrics provide insights into the performance of the database and how workloads are distributed.

[INFORMATION]
====
The **Health** tab displays for only databases on a paid tier.
This capability is not available for databases running on the Free tier.
====

[TIP]
====
When viewing information about a database on the *Health* page, click the ellipsis next to the database name to view connection details.
====

== Procedure
. Open a browser, navigate to https://astra.datastax.com[DataStax Astra], and log in.
. On the *Databases* page, select the database name to view details for.
Details for the database display on the *Summary* tab.
. To view health metrics for the database, select the *Health* tab.
. Select the time period and type of data to display in the health metrics for.
Data types to display include average, minimum, and maximum.
. Zoom in or out on the metrics, or click the time selector to change the period that metrics display for.

=== Results
Metrics for the database display in the Grafana dashboard embedded in the DataStax Cloud console.
To view more granular metrics, hover over a specific time in the graph.
Read and write latencies display in nanoseconds.

== View health dashboard in a full browser window
. Select *Cycle View Mode* in the upper right corner.
This selection displays the cycle view.
. Press *Esc*.
. Select *Share Dashboard* in the upper right corner.
. Copy the URL.
. Paste the URL in a new browser tab or window to see the dashboard.
