site:
  title: DataStax Pulsar Connector
  url: https://docs.datastax.com/en/pulsar-connector
  # The keys.segmentIo site key must be in the site-publish playbook of each
  # docset. This loads Segment into the docset build, and is a requirement for
  # collecting site analytics.
  keys:
    segmentIo: d24gQtyKIUu5mLdkp11xjfiXLhRqx0HH

output:
  # Bsys requires the output.dir in the site-publish playbook to be specifically
  # set to "~/work/<repo-name>/build/site". This is because bsys clones the
  # content source repo into "/work", and then looks for the Antora-generated
  # site in "build/site" within the repo directory when deploying/syncing.
  dir: '~/work/pulsar-sink-docs/build/site'

content:
  edit_url: false
  sources:
  - url: '~/work/pulsar-sink-docs'
    branches: HEAD
    start_path: docs-src/pulsar-sink-core

ui:
  bundle:
    url: https://github.com/riptano/antora-ui-docs/releases/latest/download/ui-bundle.zip
    snapshot: true
  # Uncomment the "supplemental_files" line below ONLY IF you're trying to
  # change the banner logo to something other than the default logo provided by
  # the UI bundle. NOTE: The non-default logo must be named "logo.svg" and be
  # located @ "playbooks/supplemental-ui/img/logo.svg".
  #supplemental_files: ~/work/pulsar-sink-docs/playbooks/supplemental-ui
  output_dir: assets

asciidoc:
  attributes:
    page-pagination: ''
    sectanchors: ''
    sectlinks: ''
    idprefix: ''
    idseparator: '-'

    support_url: 'https://support.datastax.com'
    astra_docs_base_url: 'https://docs.datastax.com/en/astra/docs'

    # The "glossary-url" attribute below is used by writers when linking to a
    # term in the glossary. Referencing this attribute in an adoc file will
    # automatically insert the root URL where the glossary pages are located.
    # For example, the following syntax will generate a link to the glossary
    # page for "agent": {glossary-url}agent[agent,window="_blank"]
    glossary-url: 'https://docs.datastax.com/en/glossary/docs/index.html#'

    # Bsys requires the URLs of the content source repos of the current docset
    # to be listed as attributes in the site-publish playbook in the form
    # "<repo-name>: 'ssh://github.com/<org-name>/<repo-name>.git'".
    pulsar-sink-docs: 'ssh://github.com/datastax/pulsar-sink-docs.git'

  extensions:
  - '@asciidoctor/tabs'
